// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hier_func_fifo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        fifo_input_line_0_V_V,
        fifo_input_line_1_V_V_dout,
        fifo_input_line_1_V_V_empty_n,
        fifo_input_line_1_V_V_read,
        fifo_input_line_2_V_V_dout,
        fifo_input_line_2_V_V_empty_n,
        fifo_input_line_2_V_V_read,
        fifo_input_line_3_V_V_dout,
        fifo_input_line_3_V_V_empty_n,
        fifo_input_line_3_V_V_read,
        fifo_input_line_4_V_V_dout,
        fifo_input_line_4_V_V_empty_n,
        fifo_input_line_4_V_V_read,
        fifo_input_line_5_V_V_dout,
        fifo_input_line_5_V_V_empty_n,
        fifo_input_line_5_V_V_read,
        fifo_input_line_6_V_V_dout,
        fifo_input_line_6_V_V_empty_n,
        fifo_input_line_6_V_V_read,
        fifo_input_line_7_V_V_dout,
        fifo_input_line_7_V_V_empty_n,
        fifo_input_line_7_V_V_read,
        fifo_input_line_8_V_V_dout,
        fifo_input_line_8_V_V_empty_n,
        fifo_input_line_8_V_V_read,
        fifo_input_line_9_V_V_dout,
        fifo_input_line_9_V_V_empty_n,
        fifo_input_line_9_V_V_read,
        fifo_input_line_10_V_V_dout,
        fifo_input_line_10_V_V_empty_n,
        fifo_input_line_10_V_V_read,
        fifo_input_line_11_V_V_dout,
        fifo_input_line_11_V_V_empty_n,
        fifo_input_line_11_V_V_read,
        fifo_input_line_12_V_V_dout,
        fifo_input_line_12_V_V_empty_n,
        fifo_input_line_12_V_V_read,
        fifo_input_line_13_V_V_dout,
        fifo_input_line_13_V_V_empty_n,
        fifo_input_line_13_V_V_read,
        fifo_input_line_14_V_V_dout,
        fifo_input_line_14_V_V_empty_n,
        fifo_input_line_14_V_V_read,
        fifo_input_line_15_V_V_dout,
        fifo_input_line_15_V_V_empty_n,
        fifo_input_line_15_V_V_read,
        fifo_output_V_V_TDATA,
        fifo_output_V_V_TVALID,
        fifo_output_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [9:0] fifo_input_line_0_V_V;
input  [9:0] fifo_input_line_1_V_V_dout;
input   fifo_input_line_1_V_V_empty_n;
output   fifo_input_line_1_V_V_read;
input  [9:0] fifo_input_line_2_V_V_dout;
input   fifo_input_line_2_V_V_empty_n;
output   fifo_input_line_2_V_V_read;
input  [9:0] fifo_input_line_3_V_V_dout;
input   fifo_input_line_3_V_V_empty_n;
output   fifo_input_line_3_V_V_read;
input  [9:0] fifo_input_line_4_V_V_dout;
input   fifo_input_line_4_V_V_empty_n;
output   fifo_input_line_4_V_V_read;
input  [9:0] fifo_input_line_5_V_V_dout;
input   fifo_input_line_5_V_V_empty_n;
output   fifo_input_line_5_V_V_read;
input  [9:0] fifo_input_line_6_V_V_dout;
input   fifo_input_line_6_V_V_empty_n;
output   fifo_input_line_6_V_V_read;
input  [9:0] fifo_input_line_7_V_V_dout;
input   fifo_input_line_7_V_V_empty_n;
output   fifo_input_line_7_V_V_read;
input  [9:0] fifo_input_line_8_V_V_dout;
input   fifo_input_line_8_V_V_empty_n;
output   fifo_input_line_8_V_V_read;
input  [9:0] fifo_input_line_9_V_V_dout;
input   fifo_input_line_9_V_V_empty_n;
output   fifo_input_line_9_V_V_read;
input  [9:0] fifo_input_line_10_V_V_dout;
input   fifo_input_line_10_V_V_empty_n;
output   fifo_input_line_10_V_V_read;
input  [9:0] fifo_input_line_11_V_V_dout;
input   fifo_input_line_11_V_V_empty_n;
output   fifo_input_line_11_V_V_read;
input  [9:0] fifo_input_line_12_V_V_dout;
input   fifo_input_line_12_V_V_empty_n;
output   fifo_input_line_12_V_V_read;
input  [9:0] fifo_input_line_13_V_V_dout;
input   fifo_input_line_13_V_V_empty_n;
output   fifo_input_line_13_V_V_read;
input  [9:0] fifo_input_line_14_V_V_dout;
input   fifo_input_line_14_V_V_empty_n;
output   fifo_input_line_14_V_V_read;
input  [9:0] fifo_input_line_15_V_V_dout;
input   fifo_input_line_15_V_V_empty_n;
output   fifo_input_line_15_V_V_read;
output  [15:0] fifo_output_V_V_TDATA;
output   fifo_output_V_V_TVALID;
input   fifo_output_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg fifo_input_line_1_V_V_read;
reg fifo_input_line_2_V_V_read;
reg fifo_input_line_3_V_V_read;
reg fifo_input_line_4_V_V_read;
reg fifo_input_line_5_V_V_read;
reg fifo_input_line_6_V_V_read;
reg fifo_input_line_7_V_V_read;
reg fifo_input_line_8_V_V_read;
reg fifo_input_line_9_V_V_read;
reg fifo_input_line_10_V_V_read;
reg fifo_input_line_11_V_V_read;
reg fifo_input_line_12_V_V_read;
reg fifo_input_line_13_V_V_read;
reg fifo_input_line_14_V_V_read;
reg fifo_input_line_15_V_V_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] fifo_output_V_V_1_data_out;
reg    fifo_output_V_V_1_vld_in;
wire    fifo_output_V_V_1_vld_out;
wire    fifo_output_V_V_1_ack_in;
wire    fifo_output_V_V_1_ack_out;
reg   [15:0] fifo_output_V_V_1_payload_A;
reg   [15:0] fifo_output_V_V_1_payload_B;
reg    fifo_output_V_V_1_sel_rd;
reg    fifo_output_V_V_1_sel_wr;
wire    fifo_output_V_V_1_sel;
wire    fifo_output_V_V_1_load_A;
wire    fifo_output_V_V_1_load_B;
reg   [1:0] fifo_output_V_V_1_state;
wire    fifo_output_V_V_1_state_cmp_full;
reg    fifo_input_line_1_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln6_fu_460_p2;
wire   [3:0] trunc_ln114_fu_486_p1;
reg   [0:0] ap_phi_mux_tmp_16_phi_fu_372_p32;
reg    fifo_input_line_2_V_V_blk_n;
reg    fifo_input_line_3_V_V_blk_n;
reg    fifo_input_line_4_V_V_blk_n;
reg    fifo_input_line_5_V_V_blk_n;
reg    fifo_input_line_6_V_V_blk_n;
reg    fifo_input_line_7_V_V_blk_n;
reg    fifo_input_line_8_V_V_blk_n;
reg    fifo_input_line_9_V_V_blk_n;
reg    fifo_input_line_10_V_V_blk_n;
reg    fifo_input_line_11_V_V_blk_n;
reg    fifo_input_line_12_V_V_blk_n;
reg    fifo_input_line_13_V_V_blk_n;
reg    fifo_input_line_14_V_V_blk_n;
reg    fifo_input_line_15_V_V_blk_n;
reg    fifo_output_V_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] tmp_16_reg_369;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] tmp_16_reg_369_pp0_iter1_reg;
reg   [12:0] indvar_flatten_reg_347;
reg   [4:0] buffer_num_0_reg_358;
reg    ap_predicate_op68_read_state2;
reg    ap_predicate_op70_read_state2;
reg    ap_predicate_op72_read_state2;
reg    ap_predicate_op74_read_state2;
reg    ap_predicate_op76_read_state2;
reg    ap_predicate_op78_read_state2;
reg    ap_predicate_op80_read_state2;
reg    ap_predicate_op82_read_state2;
reg    ap_predicate_op84_read_state2;
reg    ap_predicate_op86_read_state2;
reg    ap_predicate_op88_read_state2;
reg    ap_predicate_op90_read_state2;
reg    ap_predicate_op92_read_state2;
reg    ap_predicate_op94_read_state2;
reg    ap_predicate_op98_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state3_io;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_state4_io;
reg    ap_block_pp0_stage0_11001;
wire   [12:0] add_ln6_fu_466_p2;
wire   [4:0] buffer_num_fu_490_p2;
wire   [15:0] zext_ln163_fu_496_p1;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire   [0:0] tmp5_nbreadreq_fu_228_p3;
wire   [0:0] ap_phi_reg_pp0_iter0_tmp_16_reg_369;
wire   [0:0] tmp6_nbreadreq_fu_220_p3;
wire   [0:0] tmp7_nbreadreq_fu_212_p3;
wire   [0:0] tmp8_nbreadreq_fu_204_p3;
wire   [0:0] tmp9_nbreadreq_fu_196_p3;
wire   [0:0] tmp1_nbreadreq_fu_188_p3;
wire   [0:0] tmp2_nbreadreq_fu_180_p3;
wire   [0:0] tmp3_nbreadreq_fu_172_p3;
wire   [0:0] tmp4_nbreadreq_fu_164_p3;
wire   [0:0] tmp10_nbreadreq_fu_156_p3;
wire   [0:0] tmp11_nbreadreq_fu_148_p3;
wire   [0:0] tmp12_nbreadreq_fu_140_p3;
wire   [0:0] tmp13_nbreadreq_fu_132_p3;
wire   [0:0] tmp14_nbreadreq_fu_124_p3;
wire   [0:0] tmp15_nbreadreq_fu_116_p3;
wire   [0:0] tmp_nbreadreq_fu_236_p3;
wire   [9:0] ap_phi_reg_pp0_iter0_temp_V_reg_423;
reg   [9:0] ap_phi_reg_pp0_iter1_temp_V_reg_423;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln7_fu_472_p2;
wire   [4:0] buffer_num_0_mid2_fu_478_p3;
wire    ap_CS_fsm_state5;
reg    ap_block_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_634;
reg    ap_condition_258;
reg    ap_condition_252;
reg    ap_condition_246;
reg    ap_condition_240;
reg    ap_condition_234;
reg    ap_condition_228;
reg    ap_condition_222;
reg    ap_condition_216;
reg    ap_condition_210;
reg    ap_condition_204;
reg    ap_condition_198;
reg    ap_condition_192;
reg    ap_condition_186;
reg    ap_condition_180;
reg    ap_condition_174;
reg    ap_condition_432;
reg    ap_condition_380;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 fifo_output_V_V_1_sel_rd = 1'b0;
#0 fifo_output_V_V_1_sel_wr = 1'b0;
#0 fifo_output_V_V_1_state = 2'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((fifo_output_V_V_1_state == 2'd1) | ((fifo_output_V_V_TREADY == 1'b0) & (fifo_output_V_V_1_state == 2'd3))) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fifo_output_V_V_1_sel_rd <= 1'b0;
    end else begin
        if (((fifo_output_V_V_1_ack_out == 1'b1) & (fifo_output_V_V_1_vld_out == 1'b1))) begin
            fifo_output_V_V_1_sel_rd <= ~fifo_output_V_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fifo_output_V_V_1_sel_wr <= 1'b0;
    end else begin
        if (((fifo_output_V_V_1_ack_in == 1'b1) & (fifo_output_V_V_1_vld_in == 1'b1))) begin
            fifo_output_V_V_1_sel_wr <= ~fifo_output_V_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fifo_output_V_V_1_state <= 2'd0;
    end else begin
        if ((((fifo_output_V_V_1_vld_in == 1'b0) & (fifo_output_V_V_1_state == 2'd2)) | ((fifo_output_V_V_1_vld_in == 1'b0) & (fifo_output_V_V_1_ack_out == 1'b1) & (fifo_output_V_V_1_state == 2'd3)))) begin
            fifo_output_V_V_1_state <= 2'd2;
        end else if ((((fifo_output_V_V_TREADY == 1'b0) & (fifo_output_V_V_1_state == 2'd1)) | ((fifo_output_V_V_TREADY == 1'b0) & (fifo_output_V_V_1_vld_in == 1'b1) & (fifo_output_V_V_1_state == 2'd3)))) begin
            fifo_output_V_V_1_state <= 2'd1;
        end else if (((~((fifo_output_V_V_1_vld_in == 1'b0) & (fifo_output_V_V_1_ack_out == 1'b1)) & ~((fifo_output_V_V_TREADY == 1'b0) & (fifo_output_V_V_1_vld_in == 1'b1)) & (fifo_output_V_V_1_state == 2'd3)) | ((fifo_output_V_V_1_ack_out == 1'b1) & (fifo_output_V_V_1_state == 2'd1)) | ((fifo_output_V_V_1_vld_in == 1'b1) & (fifo_output_V_V_1_state == 2'd2)))) begin
            fifo_output_V_V_1_state <= 2'd3;
        end else begin
            fifo_output_V_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_380)) begin
        if ((1'b1 == ap_condition_432)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_0_V_V;
        end else if ((1'b1 == ap_condition_174)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_1_V_V_dout;
        end else if ((1'b1 == ap_condition_180)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_2_V_V_dout;
        end else if ((1'b1 == ap_condition_186)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_3_V_V_dout;
        end else if ((1'b1 == ap_condition_192)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_4_V_V_dout;
        end else if ((1'b1 == ap_condition_198)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_5_V_V_dout;
        end else if ((1'b1 == ap_condition_204)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_6_V_V_dout;
        end else if ((1'b1 == ap_condition_210)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_7_V_V_dout;
        end else if ((1'b1 == ap_condition_216)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_8_V_V_dout;
        end else if ((1'b1 == ap_condition_222)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_9_V_V_dout;
        end else if ((1'b1 == ap_condition_228)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_10_V_V_dout;
        end else if ((1'b1 == ap_condition_234)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_11_V_V_dout;
        end else if ((1'b1 == ap_condition_240)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_12_V_V_dout;
        end else if ((1'b1 == ap_condition_246)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_13_V_V_dout;
        end else if ((1'b1 == ap_condition_252)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_14_V_V_dout;
        end else if ((1'b1 == ap_condition_258)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= fifo_input_line_15_V_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_temp_V_reg_423 <= ap_phi_reg_pp0_iter0_temp_V_reg_423;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        buffer_num_0_reg_358 <= buffer_num_fu_490_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_num_0_reg_358 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        indvar_flatten_reg_347 <= add_ln6_fu_466_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_347 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_380)) begin
        if (((trunc_ln114_fu_486_p1 == 4'd15) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp_nbreadreq_fu_236_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd14) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp15_nbreadreq_fu_116_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd13) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp14_nbreadreq_fu_124_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd12) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp13_nbreadreq_fu_132_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd11) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp12_nbreadreq_fu_140_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd10) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp11_nbreadreq_fu_148_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd9) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp10_nbreadreq_fu_156_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd8) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp4_nbreadreq_fu_164_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd7) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp3_nbreadreq_fu_172_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd6) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp2_nbreadreq_fu_180_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd5) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp1_nbreadreq_fu_188_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd4) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp9_nbreadreq_fu_196_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd3) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp8_nbreadreq_fu_204_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd2) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp7_nbreadreq_fu_212_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp6_nbreadreq_fu_220_p3;
        end else if (((trunc_ln114_fu_486_p1 == 4'd0) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
            tmp_16_reg_369 <= tmp5_nbreadreq_fu_228_p3;
        end else if ((1'b1 == 1'b1)) begin
            tmp_16_reg_369 <= ap_phi_reg_pp0_iter0_tmp_16_reg_369;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((fifo_output_V_V_1_load_A == 1'b1)) begin
        fifo_output_V_V_1_payload_A <= zext_ln163_fu_496_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((fifo_output_V_V_1_load_B == 1'b1)) begin
        fifo_output_V_V_1_payload_B <= zext_ln163_fu_496_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_16_reg_369_pp0_iter1_reg <= tmp_16_reg_369;
    end
end

always @ (*) begin
    if ((icmp_ln6_fu_460_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((~((fifo_output_V_V_1_state == 2'd1) | ((fifo_output_V_V_TREADY == 1'b0) & (fifo_output_V_V_1_state == 2'd3))) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_634)) begin
        if ((trunc_ln114_fu_486_p1 == 4'd15)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp_nbreadreq_fu_236_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd14)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp15_nbreadreq_fu_116_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd13)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp14_nbreadreq_fu_124_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd12)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp13_nbreadreq_fu_132_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd11)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp12_nbreadreq_fu_140_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd10)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp11_nbreadreq_fu_148_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd9)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp10_nbreadreq_fu_156_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd8)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp4_nbreadreq_fu_164_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd7)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp3_nbreadreq_fu_172_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd6)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp2_nbreadreq_fu_180_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd5)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp1_nbreadreq_fu_188_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd4)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp9_nbreadreq_fu_196_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd3)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp8_nbreadreq_fu_204_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd2)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp7_nbreadreq_fu_212_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd1)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = tmp6_nbreadreq_fu_220_p3;
        end else if ((trunc_ln114_fu_486_p1 == 4'd0)) begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = 1'd0;
        end else begin
            ap_phi_mux_tmp_16_phi_fu_372_p32 = ap_phi_reg_pp0_iter0_tmp_16_reg_369;
        end
    end else begin
        ap_phi_mux_tmp_16_phi_fu_372_p32 = ap_phi_reg_pp0_iter0_tmp_16_reg_369;
    end
end

always @ (*) begin
    if ((~((fifo_output_V_V_1_state == 2'd1) | ((fifo_output_V_V_TREADY == 1'b0) & (fifo_output_V_V_1_state == 2'd3))) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd10) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_10_V_V_blk_n = fifo_input_line_10_V_V_empty_n;
    end else begin
        fifo_input_line_10_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op76_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_10_V_V_read = 1'b1;
    end else begin
        fifo_input_line_10_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd11) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_11_V_V_blk_n = fifo_input_line_11_V_V_empty_n;
    end else begin
        fifo_input_line_11_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op74_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_11_V_V_read = 1'b1;
    end else begin
        fifo_input_line_11_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd12) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_12_V_V_blk_n = fifo_input_line_12_V_V_empty_n;
    end else begin
        fifo_input_line_12_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op72_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_12_V_V_read = 1'b1;
    end else begin
        fifo_input_line_12_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd13) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_13_V_V_blk_n = fifo_input_line_13_V_V_empty_n;
    end else begin
        fifo_input_line_13_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op70_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_13_V_V_read = 1'b1;
    end else begin
        fifo_input_line_13_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd14) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_14_V_V_blk_n = fifo_input_line_14_V_V_empty_n;
    end else begin
        fifo_input_line_14_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op68_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_14_V_V_read = 1'b1;
    end else begin
        fifo_input_line_14_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd15) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_15_V_V_blk_n = fifo_input_line_15_V_V_empty_n;
    end else begin
        fifo_input_line_15_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op98_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_15_V_V_read = 1'b1;
    end else begin
        fifo_input_line_15_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_1_V_V_blk_n = fifo_input_line_1_V_V_empty_n;
    end else begin
        fifo_input_line_1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op94_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_1_V_V_read = 1'b1;
    end else begin
        fifo_input_line_1_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd2) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_2_V_V_blk_n = fifo_input_line_2_V_V_empty_n;
    end else begin
        fifo_input_line_2_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op92_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_2_V_V_read = 1'b1;
    end else begin
        fifo_input_line_2_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd3) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_3_V_V_blk_n = fifo_input_line_3_V_V_empty_n;
    end else begin
        fifo_input_line_3_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op90_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_3_V_V_read = 1'b1;
    end else begin
        fifo_input_line_3_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd4) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_4_V_V_blk_n = fifo_input_line_4_V_V_empty_n;
    end else begin
        fifo_input_line_4_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op88_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_4_V_V_read = 1'b1;
    end else begin
        fifo_input_line_4_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd5) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_5_V_V_blk_n = fifo_input_line_5_V_V_empty_n;
    end else begin
        fifo_input_line_5_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op86_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_5_V_V_read = 1'b1;
    end else begin
        fifo_input_line_5_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd6) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_6_V_V_blk_n = fifo_input_line_6_V_V_empty_n;
    end else begin
        fifo_input_line_6_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op84_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_6_V_V_read = 1'b1;
    end else begin
        fifo_input_line_6_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd7) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_7_V_V_blk_n = fifo_input_line_7_V_V_empty_n;
    end else begin
        fifo_input_line_7_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op82_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_7_V_V_read = 1'b1;
    end else begin
        fifo_input_line_7_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd8) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_8_V_V_blk_n = fifo_input_line_8_V_V_empty_n;
    end else begin
        fifo_input_line_8_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op80_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_8_V_V_read = 1'b1;
    end else begin
        fifo_input_line_8_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln114_fu_486_p1 == 4'd9) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0))) begin
        fifo_input_line_9_V_V_blk_n = fifo_input_line_9_V_V_empty_n;
    end else begin
        fifo_input_line_9_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op78_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fifo_input_line_9_V_V_read = 1'b1;
    end else begin
        fifo_input_line_9_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((fifo_output_V_V_1_sel == 1'b1)) begin
        fifo_output_V_V_1_data_out = fifo_output_V_V_1_payload_B;
    end else begin
        fifo_output_V_V_1_data_out = fifo_output_V_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_16_reg_369 == 1'd1))) begin
        fifo_output_V_V_1_vld_in = 1'b1;
    end else begin
        fifo_output_V_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (tmp_16_reg_369_pp0_iter1_reg == 1'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (tmp_16_reg_369 == 1'd1)))) begin
        fifo_output_V_V_TDATA_blk_n = fifo_output_V_V_1_state[1'd1];
    end else begin
        fifo_output_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln6_fu_460_p2 == 1'd1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln6_fu_460_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((fifo_output_V_V_1_state == 2'd1) | ((fifo_output_V_V_TREADY == 1'b0) & (fifo_output_V_V_1_state == 2'd3))) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln6_fu_466_p2 = (indvar_flatten_reg_347 + 13'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((fifo_input_line_15_V_V_empty_n == 1'b0) & (ap_predicate_op98_read_state2 == 1'b1)) | ((fifo_input_line_1_V_V_empty_n == 1'b0) & (ap_predicate_op94_read_state2 == 1'b1)) | ((fifo_input_line_2_V_V_empty_n == 1'b0) & (ap_predicate_op92_read_state2 == 1'b1)) | ((fifo_input_line_3_V_V_empty_n == 1'b0) & (ap_predicate_op90_read_state2 == 1'b1)) | ((fifo_input_line_4_V_V_empty_n == 1'b0) & (ap_predicate_op88_read_state2 == 1'b1)) | ((fifo_input_line_5_V_V_empty_n == 1'b0) & (ap_predicate_op86_read_state2 == 1'b1)) | ((fifo_input_line_6_V_V_empty_n == 1'b0) & (ap_predicate_op84_read_state2 == 1'b1)) | ((fifo_input_line_7_V_V_empty_n == 1'b0) & (ap_predicate_op82_read_state2 == 1'b1)) | ((fifo_input_line_8_V_V_empty_n == 1'b0) & (ap_predicate_op80_read_state2 == 1'b1)) | ((fifo_input_line_9_V_V_empty_n == 1'b0) & (ap_predicate_op78_read_state2 == 1'b1)) | ((fifo_input_line_10_V_V_empty_n == 1'b0) & (ap_predicate_op76_read_state2 == 1'b1)) | ((fifo_input_line_11_V_V_empty_n == 1'b0) & (ap_predicate_op74_read_state2 == 1'b1)) | ((fifo_input_line_12_V_V_empty_n == 1'b0) & (ap_predicate_op72_read_state2 == 1'b1)) | ((fifo_input_line_13_V_V_empty_n == 1'b0) & (ap_predicate_op70_read_state2 == 1'b1)) | ((fifo_input_line_14_V_V_empty_n == 1'b0) & (ap_predicate_op68_read_state2 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state4_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state3_io) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((fifo_input_line_15_V_V_empty_n == 1'b0) & (ap_predicate_op98_read_state2 == 1'b1)) | ((fifo_input_line_1_V_V_empty_n == 1'b0) & (ap_predicate_op94_read_state2 == 1'b1)) | ((fifo_input_line_2_V_V_empty_n == 1'b0) & (ap_predicate_op92_read_state2 == 1'b1)) | ((fifo_input_line_3_V_V_empty_n == 1'b0) & (ap_predicate_op90_read_state2 == 1'b1)) | ((fifo_input_line_4_V_V_empty_n == 1'b0) & (ap_predicate_op88_read_state2 == 1'b1)) | ((fifo_input_line_5_V_V_empty_n == 1'b0) & (ap_predicate_op86_read_state2 == 1'b1)) | ((fifo_input_line_6_V_V_empty_n == 1'b0) & (ap_predicate_op84_read_state2 == 1'b1)) | ((fifo_input_line_7_V_V_empty_n == 1'b0) & (ap_predicate_op82_read_state2 == 1'b1)) | ((fifo_input_line_8_V_V_empty_n == 1'b0) & (ap_predicate_op80_read_state2 == 1'b1)) | ((fifo_input_line_9_V_V_empty_n == 1'b0) & (ap_predicate_op78_read_state2 == 1'b1)) | ((fifo_input_line_10_V_V_empty_n == 1'b0) & (ap_predicate_op76_read_state2 == 1'b1)) | ((fifo_input_line_11_V_V_empty_n == 1'b0) & (ap_predicate_op74_read_state2 == 1'b1)) | ((fifo_input_line_12_V_V_empty_n == 1'b0) & (ap_predicate_op72_read_state2 == 1'b1)) | ((fifo_input_line_13_V_V_empty_n == 1'b0) & (ap_predicate_op70_read_state2 == 1'b1)) | ((fifo_input_line_14_V_V_empty_n == 1'b0) & (ap_predicate_op68_read_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state4_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state3_io) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((fifo_input_line_15_V_V_empty_n == 1'b0) & (ap_predicate_op98_read_state2 == 1'b1)) | ((fifo_input_line_1_V_V_empty_n == 1'b0) & (ap_predicate_op94_read_state2 == 1'b1)) | ((fifo_input_line_2_V_V_empty_n == 1'b0) & (ap_predicate_op92_read_state2 == 1'b1)) | ((fifo_input_line_3_V_V_empty_n == 1'b0) & (ap_predicate_op90_read_state2 == 1'b1)) | ((fifo_input_line_4_V_V_empty_n == 1'b0) & (ap_predicate_op88_read_state2 == 1'b1)) | ((fifo_input_line_5_V_V_empty_n == 1'b0) & (ap_predicate_op86_read_state2 == 1'b1)) | ((fifo_input_line_6_V_V_empty_n == 1'b0) & (ap_predicate_op84_read_state2 == 1'b1)) | ((fifo_input_line_7_V_V_empty_n == 1'b0) & (ap_predicate_op82_read_state2 == 1'b1)) | ((fifo_input_line_8_V_V_empty_n == 1'b0) & (ap_predicate_op80_read_state2 == 1'b1)) | ((fifo_input_line_9_V_V_empty_n == 1'b0) & (ap_predicate_op78_read_state2 == 1'b1)) | ((fifo_input_line_10_V_V_empty_n == 1'b0) & (ap_predicate_op76_read_state2 == 1'b1)) | ((fifo_input_line_11_V_V_empty_n == 1'b0) & (ap_predicate_op74_read_state2 == 1'b1)) | ((fifo_input_line_12_V_V_empty_n == 1'b0) & (ap_predicate_op72_read_state2 == 1'b1)) | ((fifo_input_line_13_V_V_empty_n == 1'b0) & (ap_predicate_op70_read_state2 == 1'b1)) | ((fifo_input_line_14_V_V_empty_n == 1'b0) & (ap_predicate_op68_read_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (((fifo_input_line_15_V_V_empty_n == 1'b0) & (ap_predicate_op98_read_state2 == 1'b1)) | ((fifo_input_line_1_V_V_empty_n == 1'b0) & (ap_predicate_op94_read_state2 == 1'b1)) | ((fifo_input_line_2_V_V_empty_n == 1'b0) & (ap_predicate_op92_read_state2 == 1'b1)) | ((fifo_input_line_3_V_V_empty_n == 1'b0) & (ap_predicate_op90_read_state2 == 1'b1)) | ((fifo_input_line_4_V_V_empty_n == 1'b0) & (ap_predicate_op88_read_state2 == 1'b1)) | ((fifo_input_line_5_V_V_empty_n == 1'b0) & (ap_predicate_op86_read_state2 == 1'b1)) | ((fifo_input_line_6_V_V_empty_n == 1'b0) & (ap_predicate_op84_read_state2 == 1'b1)) | ((fifo_input_line_7_V_V_empty_n == 1'b0) & (ap_predicate_op82_read_state2 == 1'b1)) | ((fifo_input_line_8_V_V_empty_n == 1'b0) & (ap_predicate_op80_read_state2 == 1'b1)) | ((fifo_input_line_9_V_V_empty_n == 1'b0) & (ap_predicate_op78_read_state2 == 1'b1)) | ((fifo_input_line_10_V_V_empty_n == 1'b0) & (ap_predicate_op76_read_state2 == 1'b1)) | ((fifo_input_line_11_V_V_empty_n == 1'b0) & (ap_predicate_op74_read_state2 == 1'b1)) | ((fifo_input_line_12_V_V_empty_n == 1'b0) & (ap_predicate_op72_read_state2 == 1'b1)) | ((fifo_input_line_13_V_V_empty_n == 1'b0) & (ap_predicate_op70_read_state2 == 1'b1)) | ((fifo_input_line_14_V_V_empty_n == 1'b0) & (ap_predicate_op68_read_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_io = ((fifo_output_V_V_1_ack_in == 1'b0) & (tmp_16_reg_369 == 1'd1));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((fifo_output_V_V_1_ack_in == 1'b0) & (tmp_16_reg_369_pp0_iter1_reg == 1'd1));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5 = ((fifo_output_V_V_1_state == 2'd1) | ((fifo_output_V_V_TREADY == 1'b0) & (fifo_output_V_V_1_state == 2'd3)));
end

always @ (*) begin
    ap_condition_174 = ((trunc_ln114_fu_486_p1 == 4'd1) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_180 = ((trunc_ln114_fu_486_p1 == 4'd2) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_186 = ((trunc_ln114_fu_486_p1 == 4'd3) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_192 = ((trunc_ln114_fu_486_p1 == 4'd4) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_198 = ((trunc_ln114_fu_486_p1 == 4'd5) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_204 = ((trunc_ln114_fu_486_p1 == 4'd6) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_210 = ((trunc_ln114_fu_486_p1 == 4'd7) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_216 = ((trunc_ln114_fu_486_p1 == 4'd8) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_222 = ((trunc_ln114_fu_486_p1 == 4'd9) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_228 = ((trunc_ln114_fu_486_p1 == 4'd10) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_234 = ((trunc_ln114_fu_486_p1 == 4'd11) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_240 = ((trunc_ln114_fu_486_p1 == 4'd12) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_246 = ((trunc_ln114_fu_486_p1 == 4'd13) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_252 = ((trunc_ln114_fu_486_p1 == 4'd14) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_258 = ((trunc_ln114_fu_486_p1 == 4'd15) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_380 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_432 = ((trunc_ln114_fu_486_p1 == 4'd0) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_634 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln6_fu_460_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_temp_V_reg_423 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_16_reg_369 = 'bx;

always @ (*) begin
    ap_predicate_op68_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd14) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op70_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd13) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op72_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd12) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op74_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd11) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op76_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd10) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op78_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd9) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op80_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd8) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op82_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd7) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op84_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd6) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op86_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd5) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op88_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd4) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op90_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd3) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op92_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd2) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op94_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd1) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op98_read_state2 = ((trunc_ln114_fu_486_p1 == 4'd15) & (ap_phi_mux_tmp_16_phi_fu_372_p32 == 1'd1) & (icmp_ln6_fu_460_p2 == 1'd0));
end

assign buffer_num_0_mid2_fu_478_p3 = ((icmp_ln7_fu_472_p2[0:0] === 1'b1) ? 5'd0 : buffer_num_0_reg_358);

assign buffer_num_fu_490_p2 = (buffer_num_0_mid2_fu_478_p3 + 5'd1);

assign fifo_output_V_V_1_ack_in = fifo_output_V_V_1_state[1'd1];

assign fifo_output_V_V_1_ack_out = fifo_output_V_V_TREADY;

assign fifo_output_V_V_1_load_A = (fifo_output_V_V_1_state_cmp_full & ~fifo_output_V_V_1_sel_wr);

assign fifo_output_V_V_1_load_B = (fifo_output_V_V_1_state_cmp_full & fifo_output_V_V_1_sel_wr);

assign fifo_output_V_V_1_sel = fifo_output_V_V_1_sel_rd;

assign fifo_output_V_V_1_state_cmp_full = ((fifo_output_V_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign fifo_output_V_V_1_vld_out = fifo_output_V_V_1_state[1'd0];

assign fifo_output_V_V_TDATA = fifo_output_V_V_1_data_out;

assign fifo_output_V_V_TVALID = fifo_output_V_V_1_state[1'd0];

assign icmp_ln6_fu_460_p2 = ((indvar_flatten_reg_347 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_472_p2 = ((buffer_num_0_reg_358 == 5'd16) ? 1'b1 : 1'b0);

assign tmp10_nbreadreq_fu_156_p3 = fifo_input_line_9_V_V_empty_n;

assign tmp11_nbreadreq_fu_148_p3 = fifo_input_line_10_V_V_empty_n;

assign tmp12_nbreadreq_fu_140_p3 = fifo_input_line_11_V_V_empty_n;

assign tmp13_nbreadreq_fu_132_p3 = fifo_input_line_12_V_V_empty_n;

assign tmp14_nbreadreq_fu_124_p3 = fifo_input_line_13_V_V_empty_n;

assign tmp15_nbreadreq_fu_116_p3 = fifo_input_line_14_V_V_empty_n;

assign tmp1_nbreadreq_fu_188_p3 = fifo_input_line_5_V_V_empty_n;

assign tmp2_nbreadreq_fu_180_p3 = fifo_input_line_6_V_V_empty_n;

assign tmp3_nbreadreq_fu_172_p3 = fifo_input_line_7_V_V_empty_n;

assign tmp4_nbreadreq_fu_164_p3 = fifo_input_line_8_V_V_empty_n;

assign tmp5_nbreadreq_fu_228_p3 = 1'd0;

assign tmp6_nbreadreq_fu_220_p3 = fifo_input_line_1_V_V_empty_n;

assign tmp7_nbreadreq_fu_212_p3 = fifo_input_line_2_V_V_empty_n;

assign tmp8_nbreadreq_fu_204_p3 = fifo_input_line_3_V_V_empty_n;

assign tmp9_nbreadreq_fu_196_p3 = fifo_input_line_4_V_V_empty_n;

assign tmp_nbreadreq_fu_236_p3 = fifo_input_line_15_V_V_empty_n;

assign trunc_ln114_fu_486_p1 = buffer_num_0_mid2_fu_478_p3[3:0];

assign zext_ln163_fu_496_p1 = ap_phi_reg_pp0_iter1_temp_V_reg_423;

endmodule //hier_func_fifo
