// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tancalc_dataflow_parent_loop_proc (
        m_axi_input_V_AWVALID,
        m_axi_input_V_AWREADY,
        m_axi_input_V_AWADDR,
        m_axi_input_V_AWID,
        m_axi_input_V_AWLEN,
        m_axi_input_V_AWSIZE,
        m_axi_input_V_AWBURST,
        m_axi_input_V_AWLOCK,
        m_axi_input_V_AWCACHE,
        m_axi_input_V_AWPROT,
        m_axi_input_V_AWQOS,
        m_axi_input_V_AWREGION,
        m_axi_input_V_AWUSER,
        m_axi_input_V_WVALID,
        m_axi_input_V_WREADY,
        m_axi_input_V_WDATA,
        m_axi_input_V_WSTRB,
        m_axi_input_V_WLAST,
        m_axi_input_V_WID,
        m_axi_input_V_WUSER,
        m_axi_input_V_ARVALID,
        m_axi_input_V_ARREADY,
        m_axi_input_V_ARADDR,
        m_axi_input_V_ARID,
        m_axi_input_V_ARLEN,
        m_axi_input_V_ARSIZE,
        m_axi_input_V_ARBURST,
        m_axi_input_V_ARLOCK,
        m_axi_input_V_ARCACHE,
        m_axi_input_V_ARPROT,
        m_axi_input_V_ARQOS,
        m_axi_input_V_ARREGION,
        m_axi_input_V_ARUSER,
        m_axi_input_V_RVALID,
        m_axi_input_V_RREADY,
        m_axi_input_V_RDATA,
        m_axi_input_V_RLAST,
        m_axi_input_V_RID,
        m_axi_input_V_RUSER,
        m_axi_input_V_RRESP,
        m_axi_input_V_BVALID,
        m_axi_input_V_BREADY,
        m_axi_input_V_BRESP,
        m_axi_input_V_BID,
        m_axi_input_V_BUSER,
        input_V_offset,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        p_read50,
        p_read51,
        p_read52,
        p_read53,
        p_read54,
        p_read55,
        p_read56,
        p_read57,
        p_read58,
        p_read59,
        p_read60,
        p_read61,
        p_read62,
        p_read63,
        p_read64,
        p_read65,
        p_read66,
        p_read67,
        p_read68,
        p_read69,
        p_read70,
        p_read71,
        p_read72,
        p_read73,
        p_read74,
        p_read75,
        p_read76,
        p_read77,
        p_read78,
        p_read79,
        p_read80,
        p_read81,
        p_read82,
        p_read83,
        p_read84,
        p_read85,
        p_read86,
        p_read87,
        p_read88,
        p_read89,
        p_read90,
        p_read91,
        p_read92,
        p_read93,
        p_read94,
        p_read95,
        p_read96,
        p_read97,
        p_read98,
        p_read99,
        p_read100,
        p_read101,
        p_read102,
        p_read103,
        p_read104,
        p_read105,
        p_read106,
        p_read107,
        p_read108,
        p_read109,
        p_read110,
        p_read111,
        p_read112,
        p_read113,
        p_read114,
        p_read115,
        p_read116,
        p_read117,
        p_read118,
        p_read119,
        p_read120,
        p_read121,
        p_read122,
        p_read123,
        p_read124,
        p_read125,
        p_read126,
        p_read127,
        result_i,
        result_o,
        ap_clk,
        ap_rst,
        input_V_offset_ap_vld,
        p_read_ap_vld,
        p_read1_ap_vld,
        p_read2_ap_vld,
        p_read3_ap_vld,
        p_read4_ap_vld,
        p_read5_ap_vld,
        p_read6_ap_vld,
        p_read7_ap_vld,
        p_read8_ap_vld,
        p_read9_ap_vld,
        p_read10_ap_vld,
        p_read11_ap_vld,
        p_read12_ap_vld,
        p_read13_ap_vld,
        p_read14_ap_vld,
        p_read15_ap_vld,
        p_read16_ap_vld,
        p_read17_ap_vld,
        p_read18_ap_vld,
        p_read19_ap_vld,
        p_read20_ap_vld,
        p_read21_ap_vld,
        p_read22_ap_vld,
        p_read23_ap_vld,
        p_read24_ap_vld,
        p_read25_ap_vld,
        p_read26_ap_vld,
        p_read27_ap_vld,
        p_read28_ap_vld,
        p_read29_ap_vld,
        p_read30_ap_vld,
        p_read31_ap_vld,
        p_read32_ap_vld,
        p_read33_ap_vld,
        p_read34_ap_vld,
        p_read35_ap_vld,
        p_read36_ap_vld,
        p_read37_ap_vld,
        p_read38_ap_vld,
        p_read39_ap_vld,
        p_read40_ap_vld,
        p_read41_ap_vld,
        p_read42_ap_vld,
        p_read43_ap_vld,
        p_read44_ap_vld,
        p_read45_ap_vld,
        p_read46_ap_vld,
        p_read47_ap_vld,
        p_read48_ap_vld,
        p_read49_ap_vld,
        p_read50_ap_vld,
        p_read51_ap_vld,
        p_read52_ap_vld,
        p_read53_ap_vld,
        p_read54_ap_vld,
        p_read55_ap_vld,
        p_read56_ap_vld,
        p_read57_ap_vld,
        p_read58_ap_vld,
        p_read59_ap_vld,
        p_read60_ap_vld,
        p_read61_ap_vld,
        p_read62_ap_vld,
        p_read63_ap_vld,
        p_read64_ap_vld,
        p_read65_ap_vld,
        p_read66_ap_vld,
        p_read67_ap_vld,
        p_read68_ap_vld,
        p_read69_ap_vld,
        p_read70_ap_vld,
        p_read71_ap_vld,
        p_read72_ap_vld,
        p_read73_ap_vld,
        p_read74_ap_vld,
        p_read75_ap_vld,
        p_read76_ap_vld,
        p_read77_ap_vld,
        p_read78_ap_vld,
        p_read79_ap_vld,
        p_read80_ap_vld,
        p_read81_ap_vld,
        p_read82_ap_vld,
        p_read83_ap_vld,
        p_read84_ap_vld,
        p_read85_ap_vld,
        p_read86_ap_vld,
        p_read87_ap_vld,
        p_read88_ap_vld,
        p_read89_ap_vld,
        p_read90_ap_vld,
        p_read91_ap_vld,
        p_read92_ap_vld,
        p_read93_ap_vld,
        p_read94_ap_vld,
        p_read95_ap_vld,
        p_read96_ap_vld,
        p_read97_ap_vld,
        p_read98_ap_vld,
        p_read99_ap_vld,
        p_read100_ap_vld,
        p_read101_ap_vld,
        p_read102_ap_vld,
        p_read103_ap_vld,
        p_read104_ap_vld,
        p_read105_ap_vld,
        p_read106_ap_vld,
        p_read107_ap_vld,
        p_read108_ap_vld,
        p_read109_ap_vld,
        p_read110_ap_vld,
        p_read111_ap_vld,
        p_read112_ap_vld,
        p_read113_ap_vld,
        p_read114_ap_vld,
        p_read115_ap_vld,
        p_read116_ap_vld,
        p_read117_ap_vld,
        p_read118_ap_vld,
        p_read119_ap_vld,
        p_read120_ap_vld,
        p_read121_ap_vld,
        p_read122_ap_vld,
        p_read123_ap_vld,
        p_read124_ap_vld,
        p_read125_ap_vld,
        p_read126_ap_vld,
        p_read127_ap_vld,
        result_i_ap_vld,
        result_o_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_input_V_AWVALID;
input   m_axi_input_V_AWREADY;
output  [63:0] m_axi_input_V_AWADDR;
output  [0:0] m_axi_input_V_AWID;
output  [31:0] m_axi_input_V_AWLEN;
output  [2:0] m_axi_input_V_AWSIZE;
output  [1:0] m_axi_input_V_AWBURST;
output  [1:0] m_axi_input_V_AWLOCK;
output  [3:0] m_axi_input_V_AWCACHE;
output  [2:0] m_axi_input_V_AWPROT;
output  [3:0] m_axi_input_V_AWQOS;
output  [3:0] m_axi_input_V_AWREGION;
output  [0:0] m_axi_input_V_AWUSER;
output   m_axi_input_V_WVALID;
input   m_axi_input_V_WREADY;
output  [511:0] m_axi_input_V_WDATA;
output  [63:0] m_axi_input_V_WSTRB;
output   m_axi_input_V_WLAST;
output  [0:0] m_axi_input_V_WID;
output  [0:0] m_axi_input_V_WUSER;
output   m_axi_input_V_ARVALID;
input   m_axi_input_V_ARREADY;
output  [63:0] m_axi_input_V_ARADDR;
output  [0:0] m_axi_input_V_ARID;
output  [31:0] m_axi_input_V_ARLEN;
output  [2:0] m_axi_input_V_ARSIZE;
output  [1:0] m_axi_input_V_ARBURST;
output  [1:0] m_axi_input_V_ARLOCK;
output  [3:0] m_axi_input_V_ARCACHE;
output  [2:0] m_axi_input_V_ARPROT;
output  [3:0] m_axi_input_V_ARQOS;
output  [3:0] m_axi_input_V_ARREGION;
output  [0:0] m_axi_input_V_ARUSER;
input   m_axi_input_V_RVALID;
output   m_axi_input_V_RREADY;
input  [511:0] m_axi_input_V_RDATA;
input   m_axi_input_V_RLAST;
input  [0:0] m_axi_input_V_RID;
input  [0:0] m_axi_input_V_RUSER;
input  [1:0] m_axi_input_V_RRESP;
input   m_axi_input_V_BVALID;
output   m_axi_input_V_BREADY;
input  [1:0] m_axi_input_V_BRESP;
input  [0:0] m_axi_input_V_BID;
input  [0:0] m_axi_input_V_BUSER;
input  [57:0] input_V_offset;
input  [1023:0] p_read;
input  [1023:0] p_read1;
input  [1023:0] p_read2;
input  [1023:0] p_read3;
input  [1023:0] p_read4;
input  [1023:0] p_read5;
input  [1023:0] p_read6;
input  [1023:0] p_read7;
input  [1023:0] p_read8;
input  [1023:0] p_read9;
input  [1023:0] p_read10;
input  [1023:0] p_read11;
input  [1023:0] p_read12;
input  [1023:0] p_read13;
input  [1023:0] p_read14;
input  [1023:0] p_read15;
input  [1023:0] p_read16;
input  [1023:0] p_read17;
input  [1023:0] p_read18;
input  [1023:0] p_read19;
input  [1023:0] p_read20;
input  [1023:0] p_read21;
input  [1023:0] p_read22;
input  [1023:0] p_read23;
input  [1023:0] p_read24;
input  [1023:0] p_read25;
input  [1023:0] p_read26;
input  [1023:0] p_read27;
input  [1023:0] p_read28;
input  [1023:0] p_read29;
input  [1023:0] p_read30;
input  [1023:0] p_read31;
input  [1023:0] p_read32;
input  [1023:0] p_read33;
input  [1023:0] p_read34;
input  [1023:0] p_read35;
input  [1023:0] p_read36;
input  [1023:0] p_read37;
input  [1023:0] p_read38;
input  [1023:0] p_read39;
input  [1023:0] p_read40;
input  [1023:0] p_read41;
input  [1023:0] p_read42;
input  [1023:0] p_read43;
input  [1023:0] p_read44;
input  [1023:0] p_read45;
input  [1023:0] p_read46;
input  [1023:0] p_read47;
input  [1023:0] p_read48;
input  [1023:0] p_read49;
input  [1023:0] p_read50;
input  [1023:0] p_read51;
input  [1023:0] p_read52;
input  [1023:0] p_read53;
input  [1023:0] p_read54;
input  [1023:0] p_read55;
input  [1023:0] p_read56;
input  [1023:0] p_read57;
input  [1023:0] p_read58;
input  [1023:0] p_read59;
input  [1023:0] p_read60;
input  [1023:0] p_read61;
input  [1023:0] p_read62;
input  [1023:0] p_read63;
input  [10:0] p_read64;
input  [10:0] p_read65;
input  [10:0] p_read66;
input  [10:0] p_read67;
input  [10:0] p_read68;
input  [10:0] p_read69;
input  [10:0] p_read70;
input  [10:0] p_read71;
input  [10:0] p_read72;
input  [10:0] p_read73;
input  [10:0] p_read74;
input  [10:0] p_read75;
input  [10:0] p_read76;
input  [10:0] p_read77;
input  [10:0] p_read78;
input  [10:0] p_read79;
input  [10:0] p_read80;
input  [10:0] p_read81;
input  [10:0] p_read82;
input  [10:0] p_read83;
input  [10:0] p_read84;
input  [10:0] p_read85;
input  [10:0] p_read86;
input  [10:0] p_read87;
input  [10:0] p_read88;
input  [10:0] p_read89;
input  [10:0] p_read90;
input  [10:0] p_read91;
input  [10:0] p_read92;
input  [10:0] p_read93;
input  [10:0] p_read94;
input  [10:0] p_read95;
input  [10:0] p_read96;
input  [10:0] p_read97;
input  [10:0] p_read98;
input  [10:0] p_read99;
input  [10:0] p_read100;
input  [10:0] p_read101;
input  [10:0] p_read102;
input  [10:0] p_read103;
input  [10:0] p_read104;
input  [10:0] p_read105;
input  [10:0] p_read106;
input  [10:0] p_read107;
input  [10:0] p_read108;
input  [10:0] p_read109;
input  [10:0] p_read110;
input  [10:0] p_read111;
input  [10:0] p_read112;
input  [10:0] p_read113;
input  [10:0] p_read114;
input  [10:0] p_read115;
input  [10:0] p_read116;
input  [10:0] p_read117;
input  [10:0] p_read118;
input  [10:0] p_read119;
input  [10:0] p_read120;
input  [10:0] p_read121;
input  [10:0] p_read122;
input  [10:0] p_read123;
input  [10:0] p_read124;
input  [10:0] p_read125;
input  [10:0] p_read126;
input  [10:0] p_read127;
input  [31:0] result_i;
output  [31:0] result_o;
input   ap_clk;
input   ap_rst;
input   input_V_offset_ap_vld;
input   p_read_ap_vld;
input   p_read1_ap_vld;
input   p_read2_ap_vld;
input   p_read3_ap_vld;
input   p_read4_ap_vld;
input   p_read5_ap_vld;
input   p_read6_ap_vld;
input   p_read7_ap_vld;
input   p_read8_ap_vld;
input   p_read9_ap_vld;
input   p_read10_ap_vld;
input   p_read11_ap_vld;
input   p_read12_ap_vld;
input   p_read13_ap_vld;
input   p_read14_ap_vld;
input   p_read15_ap_vld;
input   p_read16_ap_vld;
input   p_read17_ap_vld;
input   p_read18_ap_vld;
input   p_read19_ap_vld;
input   p_read20_ap_vld;
input   p_read21_ap_vld;
input   p_read22_ap_vld;
input   p_read23_ap_vld;
input   p_read24_ap_vld;
input   p_read25_ap_vld;
input   p_read26_ap_vld;
input   p_read27_ap_vld;
input   p_read28_ap_vld;
input   p_read29_ap_vld;
input   p_read30_ap_vld;
input   p_read31_ap_vld;
input   p_read32_ap_vld;
input   p_read33_ap_vld;
input   p_read34_ap_vld;
input   p_read35_ap_vld;
input   p_read36_ap_vld;
input   p_read37_ap_vld;
input   p_read38_ap_vld;
input   p_read39_ap_vld;
input   p_read40_ap_vld;
input   p_read41_ap_vld;
input   p_read42_ap_vld;
input   p_read43_ap_vld;
input   p_read44_ap_vld;
input   p_read45_ap_vld;
input   p_read46_ap_vld;
input   p_read47_ap_vld;
input   p_read48_ap_vld;
input   p_read49_ap_vld;
input   p_read50_ap_vld;
input   p_read51_ap_vld;
input   p_read52_ap_vld;
input   p_read53_ap_vld;
input   p_read54_ap_vld;
input   p_read55_ap_vld;
input   p_read56_ap_vld;
input   p_read57_ap_vld;
input   p_read58_ap_vld;
input   p_read59_ap_vld;
input   p_read60_ap_vld;
input   p_read61_ap_vld;
input   p_read62_ap_vld;
input   p_read63_ap_vld;
input   p_read64_ap_vld;
input   p_read65_ap_vld;
input   p_read66_ap_vld;
input   p_read67_ap_vld;
input   p_read68_ap_vld;
input   p_read69_ap_vld;
input   p_read70_ap_vld;
input   p_read71_ap_vld;
input   p_read72_ap_vld;
input   p_read73_ap_vld;
input   p_read74_ap_vld;
input   p_read75_ap_vld;
input   p_read76_ap_vld;
input   p_read77_ap_vld;
input   p_read78_ap_vld;
input   p_read79_ap_vld;
input   p_read80_ap_vld;
input   p_read81_ap_vld;
input   p_read82_ap_vld;
input   p_read83_ap_vld;
input   p_read84_ap_vld;
input   p_read85_ap_vld;
input   p_read86_ap_vld;
input   p_read87_ap_vld;
input   p_read88_ap_vld;
input   p_read89_ap_vld;
input   p_read90_ap_vld;
input   p_read91_ap_vld;
input   p_read92_ap_vld;
input   p_read93_ap_vld;
input   p_read94_ap_vld;
input   p_read95_ap_vld;
input   p_read96_ap_vld;
input   p_read97_ap_vld;
input   p_read98_ap_vld;
input   p_read99_ap_vld;
input   p_read100_ap_vld;
input   p_read101_ap_vld;
input   p_read102_ap_vld;
input   p_read103_ap_vld;
input   p_read104_ap_vld;
input   p_read105_ap_vld;
input   p_read106_ap_vld;
input   p_read107_ap_vld;
input   p_read108_ap_vld;
input   p_read109_ap_vld;
input   p_read110_ap_vld;
input   p_read111_ap_vld;
input   p_read112_ap_vld;
input   p_read113_ap_vld;
input   p_read114_ap_vld;
input   p_read115_ap_vld;
input   p_read116_ap_vld;
input   p_read117_ap_vld;
input   p_read118_ap_vld;
input   p_read119_ap_vld;
input   p_read120_ap_vld;
input   p_read121_ap_vld;
input   p_read122_ap_vld;
input   p_read123_ap_vld;
input   p_read124_ap_vld;
input   p_read125_ap_vld;
input   p_read126_ap_vld;
input   p_read127_ap_vld;
input   result_i_ap_vld;
output   result_o_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg ap_done;
reg ap_ready;
reg ap_idle;

wire    dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWVALID;
wire   [63:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWADDR;
wire   [0:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWID;
wire   [31:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWLEN;
wire   [2:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWSIZE;
wire   [1:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWBURST;
wire   [1:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWLOCK;
wire   [3:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWCACHE;
wire   [2:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWPROT;
wire   [3:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWQOS;
wire   [3:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWREGION;
wire   [0:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWUSER;
wire    dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WVALID;
wire   [511:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WDATA;
wire   [63:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WSTRB;
wire    dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WLAST;
wire   [0:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WID;
wire   [0:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WUSER;
wire    dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARVALID;
wire   [63:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARADDR;
wire   [0:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARID;
wire   [31:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLEN;
wire   [2:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARSIZE;
wire   [1:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARBURST;
wire   [1:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLOCK;
wire   [3:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARCACHE;
wire   [2:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARPROT;
wire   [3:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARQOS;
wire   [3:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARREGION;
wire   [0:0] dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARUSER;
wire    dataflow_in_loop_calculation_loop_U0_m_axi_input_V_RREADY;
wire    dataflow_in_loop_calculation_loop_U0_m_axi_input_V_BREADY;
wire   [31:0] dataflow_in_loop_calculation_loop_U0_result_o;
wire    dataflow_in_loop_calculation_loop_U0_ap_start;
wire    dataflow_in_loop_calculation_loop_U0_result_o_ap_vld;
wire    dataflow_in_loop_calculation_loop_U0_ap_done;
wire    dataflow_in_loop_calculation_loop_U0_ap_ready;
wire    dataflow_in_loop_calculation_loop_U0_ap_idle;
reg    dataflow_in_loop_calculation_loop_U0_ap_continue;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
reg   [16:0] loop_dataflow_input_count;
reg   [16:0] loop_dataflow_output_count;
wire   [16:0] bound_minus_1;
wire    dataflow_in_loop_calculation_loop_U0_start_full_n;
wire    dataflow_in_loop_calculation_loop_U0_start_write;

// power-on initialization
initial begin
#0 loop_dataflow_input_count = 17'd0;
#0 loop_dataflow_output_count = 17'd0;
end

tancalc_dataflow_in_loop_calculation_loop dataflow_in_loop_calculation_loop_U0(
    .m_axi_input_V_AWVALID(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWVALID),
    .m_axi_input_V_AWREADY(1'b0),
    .m_axi_input_V_AWADDR(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWADDR),
    .m_axi_input_V_AWID(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWID),
    .m_axi_input_V_AWLEN(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWLEN),
    .m_axi_input_V_AWSIZE(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWSIZE),
    .m_axi_input_V_AWBURST(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWBURST),
    .m_axi_input_V_AWLOCK(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWLOCK),
    .m_axi_input_V_AWCACHE(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWCACHE),
    .m_axi_input_V_AWPROT(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWPROT),
    .m_axi_input_V_AWQOS(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWQOS),
    .m_axi_input_V_AWREGION(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWREGION),
    .m_axi_input_V_AWUSER(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWUSER),
    .m_axi_input_V_WVALID(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WVALID),
    .m_axi_input_V_WREADY(1'b0),
    .m_axi_input_V_WDATA(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WDATA),
    .m_axi_input_V_WSTRB(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WSTRB),
    .m_axi_input_V_WLAST(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WLAST),
    .m_axi_input_V_WID(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WID),
    .m_axi_input_V_WUSER(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WUSER),
    .m_axi_input_V_ARVALID(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARVALID),
    .m_axi_input_V_ARREADY(m_axi_input_V_ARREADY),
    .m_axi_input_V_ARADDR(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARADDR),
    .m_axi_input_V_ARID(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARID),
    .m_axi_input_V_ARLEN(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLEN),
    .m_axi_input_V_ARSIZE(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARSIZE),
    .m_axi_input_V_ARBURST(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARBURST),
    .m_axi_input_V_ARLOCK(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLOCK),
    .m_axi_input_V_ARCACHE(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARCACHE),
    .m_axi_input_V_ARPROT(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARPROT),
    .m_axi_input_V_ARQOS(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARQOS),
    .m_axi_input_V_ARREGION(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARREGION),
    .m_axi_input_V_ARUSER(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARUSER),
    .m_axi_input_V_RVALID(m_axi_input_V_RVALID),
    .m_axi_input_V_RREADY(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_RREADY),
    .m_axi_input_V_RDATA(m_axi_input_V_RDATA),
    .m_axi_input_V_RLAST(m_axi_input_V_RLAST),
    .m_axi_input_V_RID(m_axi_input_V_RID),
    .m_axi_input_V_RUSER(m_axi_input_V_RUSER),
    .m_axi_input_V_RRESP(m_axi_input_V_RRESP),
    .m_axi_input_V_BVALID(1'b0),
    .m_axi_input_V_BREADY(dataflow_in_loop_calculation_loop_U0_m_axi_input_V_BREADY),
    .m_axi_input_V_BRESP(2'd0),
    .m_axi_input_V_BID(1'd0),
    .m_axi_input_V_BUSER(1'd0),
    .input_V_offset(input_V_offset),
    .ref_chunk_num_0_i(loop_dataflow_input_count),
    .p_read(p_read),
    .p_read1(p_read1),
    .p_read2(p_read2),
    .p_read3(p_read3),
    .p_read4(p_read4),
    .p_read5(p_read5),
    .p_read6(p_read6),
    .p_read7(p_read7),
    .p_read8(p_read8),
    .p_read9(p_read9),
    .p_read10(p_read10),
    .p_read11(p_read11),
    .p_read12(p_read12),
    .p_read13(p_read13),
    .p_read14(p_read14),
    .p_read15(p_read15),
    .p_read16(p_read16),
    .p_read17(p_read17),
    .p_read18(p_read18),
    .p_read19(p_read19),
    .p_read20(p_read20),
    .p_read21(p_read21),
    .p_read22(p_read22),
    .p_read23(p_read23),
    .p_read24(p_read24),
    .p_read25(p_read25),
    .p_read26(p_read26),
    .p_read27(p_read27),
    .p_read28(p_read28),
    .p_read29(p_read29),
    .p_read30(p_read30),
    .p_read31(p_read31),
    .p_read32(p_read32),
    .p_read33(p_read33),
    .p_read34(p_read34),
    .p_read35(p_read35),
    .p_read36(p_read36),
    .p_read37(p_read37),
    .p_read38(p_read38),
    .p_read39(p_read39),
    .p_read40(p_read40),
    .p_read41(p_read41),
    .p_read42(p_read42),
    .p_read43(p_read43),
    .p_read44(p_read44),
    .p_read45(p_read45),
    .p_read46(p_read46),
    .p_read47(p_read47),
    .p_read48(p_read48),
    .p_read49(p_read49),
    .p_read50(p_read50),
    .p_read51(p_read51),
    .p_read52(p_read52),
    .p_read53(p_read53),
    .p_read54(p_read54),
    .p_read55(p_read55),
    .p_read56(p_read56),
    .p_read57(p_read57),
    .p_read58(p_read58),
    .p_read59(p_read59),
    .p_read60(p_read60),
    .p_read61(p_read61),
    .p_read62(p_read62),
    .p_read63(p_read63),
    .p_read64(p_read64),
    .p_read65(p_read65),
    .p_read66(p_read66),
    .p_read67(p_read67),
    .p_read68(p_read68),
    .p_read69(p_read69),
    .p_read70(p_read70),
    .p_read71(p_read71),
    .p_read72(p_read72),
    .p_read73(p_read73),
    .p_read74(p_read74),
    .p_read75(p_read75),
    .p_read76(p_read76),
    .p_read77(p_read77),
    .p_read78(p_read78),
    .p_read79(p_read79),
    .p_read80(p_read80),
    .p_read81(p_read81),
    .p_read82(p_read82),
    .p_read83(p_read83),
    .p_read84(p_read84),
    .p_read85(p_read85),
    .p_read86(p_read86),
    .p_read87(p_read87),
    .p_read88(p_read88),
    .p_read89(p_read89),
    .p_read90(p_read90),
    .p_read91(p_read91),
    .p_read92(p_read92),
    .p_read93(p_read93),
    .p_read94(p_read94),
    .p_read95(p_read95),
    .p_read96(p_read96),
    .p_read97(p_read97),
    .p_read98(p_read98),
    .p_read99(p_read99),
    .p_read100(p_read100),
    .p_read101(p_read101),
    .p_read102(p_read102),
    .p_read103(p_read103),
    .p_read104(p_read104),
    .p_read105(p_read105),
    .p_read106(p_read106),
    .p_read107(p_read107),
    .p_read108(p_read108),
    .p_read109(p_read109),
    .p_read110(p_read110),
    .p_read111(p_read111),
    .p_read112(p_read112),
    .p_read113(p_read113),
    .p_read114(p_read114),
    .p_read115(p_read115),
    .p_read116(p_read116),
    .p_read117(p_read117),
    .p_read118(p_read118),
    .p_read119(p_read119),
    .p_read120(p_read120),
    .p_read121(p_read121),
    .p_read122(p_read122),
    .p_read123(p_read123),
    .p_read124(p_read124),
    .p_read125(p_read125),
    .p_read126(p_read126),
    .p_read127(p_read127),
    .result_i(result_i),
    .result_o(dataflow_in_loop_calculation_loop_U0_result_o),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .input_V_offset_ap_vld(input_V_offset_ap_vld),
    .ref_chunk_num_0_i_ap_vld(1'b0),
    .p_read_ap_vld(p_read_ap_vld),
    .p_read1_ap_vld(p_read1_ap_vld),
    .p_read2_ap_vld(p_read2_ap_vld),
    .p_read3_ap_vld(p_read3_ap_vld),
    .p_read4_ap_vld(p_read4_ap_vld),
    .p_read5_ap_vld(p_read5_ap_vld),
    .p_read6_ap_vld(p_read6_ap_vld),
    .p_read7_ap_vld(p_read7_ap_vld),
    .p_read8_ap_vld(p_read8_ap_vld),
    .p_read9_ap_vld(p_read9_ap_vld),
    .p_read10_ap_vld(p_read10_ap_vld),
    .p_read11_ap_vld(p_read11_ap_vld),
    .p_read12_ap_vld(p_read12_ap_vld),
    .p_read13_ap_vld(p_read13_ap_vld),
    .p_read14_ap_vld(p_read14_ap_vld),
    .p_read15_ap_vld(p_read15_ap_vld),
    .p_read16_ap_vld(p_read16_ap_vld),
    .p_read17_ap_vld(p_read17_ap_vld),
    .p_read18_ap_vld(p_read18_ap_vld),
    .p_read19_ap_vld(p_read19_ap_vld),
    .p_read20_ap_vld(p_read20_ap_vld),
    .p_read21_ap_vld(p_read21_ap_vld),
    .p_read22_ap_vld(p_read22_ap_vld),
    .p_read23_ap_vld(p_read23_ap_vld),
    .p_read24_ap_vld(p_read24_ap_vld),
    .p_read25_ap_vld(p_read25_ap_vld),
    .p_read26_ap_vld(p_read26_ap_vld),
    .p_read27_ap_vld(p_read27_ap_vld),
    .p_read28_ap_vld(p_read28_ap_vld),
    .p_read29_ap_vld(p_read29_ap_vld),
    .p_read30_ap_vld(p_read30_ap_vld),
    .p_read31_ap_vld(p_read31_ap_vld),
    .p_read32_ap_vld(p_read32_ap_vld),
    .p_read33_ap_vld(p_read33_ap_vld),
    .p_read34_ap_vld(p_read34_ap_vld),
    .p_read35_ap_vld(p_read35_ap_vld),
    .p_read36_ap_vld(p_read36_ap_vld),
    .p_read37_ap_vld(p_read37_ap_vld),
    .p_read38_ap_vld(p_read38_ap_vld),
    .p_read39_ap_vld(p_read39_ap_vld),
    .p_read40_ap_vld(p_read40_ap_vld),
    .p_read41_ap_vld(p_read41_ap_vld),
    .p_read42_ap_vld(p_read42_ap_vld),
    .p_read43_ap_vld(p_read43_ap_vld),
    .p_read44_ap_vld(p_read44_ap_vld),
    .p_read45_ap_vld(p_read45_ap_vld),
    .p_read46_ap_vld(p_read46_ap_vld),
    .p_read47_ap_vld(p_read47_ap_vld),
    .p_read48_ap_vld(p_read48_ap_vld),
    .p_read49_ap_vld(p_read49_ap_vld),
    .p_read50_ap_vld(p_read50_ap_vld),
    .p_read51_ap_vld(p_read51_ap_vld),
    .p_read52_ap_vld(p_read52_ap_vld),
    .p_read53_ap_vld(p_read53_ap_vld),
    .p_read54_ap_vld(p_read54_ap_vld),
    .p_read55_ap_vld(p_read55_ap_vld),
    .p_read56_ap_vld(p_read56_ap_vld),
    .p_read57_ap_vld(p_read57_ap_vld),
    .p_read58_ap_vld(p_read58_ap_vld),
    .p_read59_ap_vld(p_read59_ap_vld),
    .p_read60_ap_vld(p_read60_ap_vld),
    .p_read61_ap_vld(p_read61_ap_vld),
    .p_read62_ap_vld(p_read62_ap_vld),
    .p_read63_ap_vld(p_read63_ap_vld),
    .p_read64_ap_vld(p_read64_ap_vld),
    .p_read65_ap_vld(p_read65_ap_vld),
    .p_read66_ap_vld(p_read66_ap_vld),
    .p_read67_ap_vld(p_read67_ap_vld),
    .p_read68_ap_vld(p_read68_ap_vld),
    .p_read69_ap_vld(p_read69_ap_vld),
    .p_read70_ap_vld(p_read70_ap_vld),
    .p_read71_ap_vld(p_read71_ap_vld),
    .p_read72_ap_vld(p_read72_ap_vld),
    .p_read73_ap_vld(p_read73_ap_vld),
    .p_read74_ap_vld(p_read74_ap_vld),
    .p_read75_ap_vld(p_read75_ap_vld),
    .p_read76_ap_vld(p_read76_ap_vld),
    .p_read77_ap_vld(p_read77_ap_vld),
    .p_read78_ap_vld(p_read78_ap_vld),
    .p_read79_ap_vld(p_read79_ap_vld),
    .p_read80_ap_vld(p_read80_ap_vld),
    .p_read81_ap_vld(p_read81_ap_vld),
    .p_read82_ap_vld(p_read82_ap_vld),
    .p_read83_ap_vld(p_read83_ap_vld),
    .p_read84_ap_vld(p_read84_ap_vld),
    .p_read85_ap_vld(p_read85_ap_vld),
    .p_read86_ap_vld(p_read86_ap_vld),
    .p_read87_ap_vld(p_read87_ap_vld),
    .p_read88_ap_vld(p_read88_ap_vld),
    .p_read89_ap_vld(p_read89_ap_vld),
    .p_read90_ap_vld(p_read90_ap_vld),
    .p_read91_ap_vld(p_read91_ap_vld),
    .p_read92_ap_vld(p_read92_ap_vld),
    .p_read93_ap_vld(p_read93_ap_vld),
    .p_read94_ap_vld(p_read94_ap_vld),
    .p_read95_ap_vld(p_read95_ap_vld),
    .p_read96_ap_vld(p_read96_ap_vld),
    .p_read97_ap_vld(p_read97_ap_vld),
    .p_read98_ap_vld(p_read98_ap_vld),
    .p_read99_ap_vld(p_read99_ap_vld),
    .p_read100_ap_vld(p_read100_ap_vld),
    .p_read101_ap_vld(p_read101_ap_vld),
    .p_read102_ap_vld(p_read102_ap_vld),
    .p_read103_ap_vld(p_read103_ap_vld),
    .p_read104_ap_vld(p_read104_ap_vld),
    .p_read105_ap_vld(p_read105_ap_vld),
    .p_read106_ap_vld(p_read106_ap_vld),
    .p_read107_ap_vld(p_read107_ap_vld),
    .p_read108_ap_vld(p_read108_ap_vld),
    .p_read109_ap_vld(p_read109_ap_vld),
    .p_read110_ap_vld(p_read110_ap_vld),
    .p_read111_ap_vld(p_read111_ap_vld),
    .p_read112_ap_vld(p_read112_ap_vld),
    .p_read113_ap_vld(p_read113_ap_vld),
    .p_read114_ap_vld(p_read114_ap_vld),
    .p_read115_ap_vld(p_read115_ap_vld),
    .p_read116_ap_vld(p_read116_ap_vld),
    .p_read117_ap_vld(p_read117_ap_vld),
    .p_read118_ap_vld(p_read118_ap_vld),
    .p_read119_ap_vld(p_read119_ap_vld),
    .p_read120_ap_vld(p_read120_ap_vld),
    .p_read121_ap_vld(p_read121_ap_vld),
    .p_read122_ap_vld(p_read122_ap_vld),
    .p_read123_ap_vld(p_read123_ap_vld),
    .p_read124_ap_vld(p_read124_ap_vld),
    .p_read125_ap_vld(p_read125_ap_vld),
    .p_read126_ap_vld(p_read126_ap_vld),
    .p_read127_ap_vld(p_read127_ap_vld),
    .ap_start(dataflow_in_loop_calculation_loop_U0_ap_start),
    .result_i_ap_vld(result_i_ap_vld),
    .result_o_ap_vld(dataflow_in_loop_calculation_loop_U0_result_o_ap_vld),
    .ap_done(dataflow_in_loop_calculation_loop_U0_ap_done),
    .ap_ready(dataflow_in_loop_calculation_loop_U0_ap_ready),
    .ap_idle(dataflow_in_loop_calculation_loop_U0_ap_idle),
    .ap_continue(dataflow_in_loop_calculation_loop_U0_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_input_count <= 17'd0;
    end else begin
        if ((~(loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_calculation_loop_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= (loop_dataflow_input_count + 17'd1);
        end else if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_calculation_loop_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_output_count <= 17'd0;
    end else begin
        if ((~(loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_calculation_loop_U0_ap_continue == 1'b1) & (dataflow_in_loop_calculation_loop_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= (loop_dataflow_output_count + 17'd1);
        end else if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_calculation_loop_U0_ap_continue == 1'b1) & (dataflow_in_loop_calculation_loop_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= 17'd0;
        end
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_calculation_loop_U0_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == 17'd0) & (ap_start == 1'b0) & (dataflow_in_loop_calculation_loop_U0_ap_idle == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_calculation_loop_U0_ap_ready == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~(loop_dataflow_output_count == bound_minus_1) | (ap_continue == 1'b1))) begin
        dataflow_in_loop_calculation_loop_U0_ap_continue = 1'b1;
    end else begin
        dataflow_in_loop_calculation_loop_U0_ap_continue = 1'b0;
    end
end

assign ap_sync_continue = ap_continue;

assign ap_sync_done = dataflow_in_loop_calculation_loop_U0_ap_done;

assign ap_sync_ready = dataflow_in_loop_calculation_loop_U0_ap_ready;

assign bound_minus_1 = (17'd65536 - 17'd1);

assign dataflow_in_loop_calculation_loop_U0_ap_start = ap_start;

assign dataflow_in_loop_calculation_loop_U0_start_full_n = 1'b1;

assign dataflow_in_loop_calculation_loop_U0_start_write = 1'b0;

assign m_axi_input_V_ARADDR = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARADDR;

assign m_axi_input_V_ARBURST = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARBURST;

assign m_axi_input_V_ARCACHE = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARCACHE;

assign m_axi_input_V_ARID = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARID;

assign m_axi_input_V_ARLEN = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLEN;

assign m_axi_input_V_ARLOCK = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLOCK;

assign m_axi_input_V_ARPROT = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARPROT;

assign m_axi_input_V_ARQOS = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARQOS;

assign m_axi_input_V_ARREGION = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARREGION;

assign m_axi_input_V_ARSIZE = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARSIZE;

assign m_axi_input_V_ARUSER = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARUSER;

assign m_axi_input_V_ARVALID = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARVALID;

assign m_axi_input_V_AWADDR = 64'd0;

assign m_axi_input_V_AWBURST = 2'd0;

assign m_axi_input_V_AWCACHE = 4'd0;

assign m_axi_input_V_AWID = 1'd0;

assign m_axi_input_V_AWLEN = 32'd0;

assign m_axi_input_V_AWLOCK = 2'd0;

assign m_axi_input_V_AWPROT = 3'd0;

assign m_axi_input_V_AWQOS = 4'd0;

assign m_axi_input_V_AWREGION = 4'd0;

assign m_axi_input_V_AWSIZE = 3'd0;

assign m_axi_input_V_AWUSER = 1'd0;

assign m_axi_input_V_AWVALID = 1'b0;

assign m_axi_input_V_BREADY = 1'b0;

assign m_axi_input_V_RREADY = dataflow_in_loop_calculation_loop_U0_m_axi_input_V_RREADY;

assign m_axi_input_V_WDATA = 512'd0;

assign m_axi_input_V_WID = 1'd0;

assign m_axi_input_V_WLAST = 1'b0;

assign m_axi_input_V_WSTRB = 64'd0;

assign m_axi_input_V_WUSER = 1'd0;

assign m_axi_input_V_WVALID = 1'b0;

assign result_o = dataflow_in_loop_calculation_loop_U0_result_o;

assign result_o_ap_vld = dataflow_in_loop_calculation_loop_U0_result_o_ap_vld;

endmodule //tancalc_dataflow_parent_loop_proc
