// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _hier_func_popcntdata_HH_
#define _hier_func_popcntdata_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct hier_func_popcntdata : public sc_module {
    // Port declarations 3
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > x_V;
    sc_out< sc_lv<6> > ap_return;


    // Module declarations
    hier_func_popcntdata(sc_module_name name);
    SC_HAS_PROCESS(hier_func_popcntdata);

    ~hier_func_popcntdata();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > p_Result_s_fu_76_p3;
    sc_signal< sc_lv<1> > p_Result_1_fu_88_p3;
    sc_signal< sc_lv<1> > p_Result_2_fu_100_p3;
    sc_signal< sc_lv<2> > zext_ln700_fu_96_p1;
    sc_signal< sc_lv<2> > zext_ln700_3_fu_108_p1;
    sc_signal< sc_lv<2> > add_ln700_1_fu_112_p2;
    sc_signal< sc_lv<2> > zext_ln791_fu_84_p1;
    sc_signal< sc_lv<2> > add_ln700_fu_118_p2;
    sc_signal< sc_lv<1> > p_Result_3_fu_128_p3;
    sc_signal< sc_lv<1> > p_Result_4_fu_140_p3;
    sc_signal< sc_lv<1> > p_Result_5_fu_152_p3;
    sc_signal< sc_lv<1> > p_Result_6_fu_164_p3;
    sc_signal< sc_lv<3> > zext_ln700_4_fu_124_p1;
    sc_signal< sc_lv<3> > zext_ln700_5_fu_136_p1;
    sc_signal< sc_lv<2> > zext_ln791_2_fu_160_p1;
    sc_signal< sc_lv<2> > zext_ln700_6_fu_172_p1;
    sc_signal< sc_lv<2> > add_ln700_3_fu_182_p2;
    sc_signal< sc_lv<2> > zext_ln791_1_fu_148_p1;
    sc_signal< sc_lv<2> > add_ln700_4_fu_188_p2;
    sc_signal< sc_lv<3> > zext_ln700_7_fu_194_p1;
    sc_signal< sc_lv<3> > add_ln700_2_fu_176_p2;
    sc_signal< sc_lv<3> > add_ln700_5_fu_198_p2;
    sc_signal< sc_lv<1> > p_Result_7_fu_208_p3;
    sc_signal< sc_lv<1> > p_Result_8_fu_220_p3;
    sc_signal< sc_lv<1> > p_Result_9_fu_232_p3;
    sc_signal< sc_lv<1> > p_Result_s_13_fu_244_p3;
    sc_signal< sc_lv<1> > p_Result_10_fu_256_p3;
    sc_signal< sc_lv<1> > p_Result_11_fu_268_p3;
    sc_signal< sc_lv<1> > p_Result_12_fu_280_p3;
    sc_signal< sc_lv<1> > p_Result_13_fu_292_p3;
    sc_signal< sc_lv<4> > zext_ln700_8_fu_204_p1;
    sc_signal< sc_lv<4> > zext_ln700_9_fu_216_p1;
    sc_signal< sc_lv<2> > zext_ln791_3_fu_228_p1;
    sc_signal< sc_lv<2> > zext_ln791_4_fu_240_p1;
    sc_signal< sc_lv<2> > add_ln700_7_fu_310_p2;
    sc_signal< sc_lv<4> > zext_ln700_11_fu_316_p1;
    sc_signal< sc_lv<4> > add_ln700_6_fu_304_p2;
    sc_signal< sc_lv<2> > zext_ln791_5_fu_252_p1;
    sc_signal< sc_lv<2> > zext_ln791_6_fu_264_p1;
    sc_signal< sc_lv<2> > add_ln700_9_fu_326_p2;
    sc_signal< sc_lv<2> > zext_ln791_8_fu_288_p1;
    sc_signal< sc_lv<2> > zext_ln700_10_fu_300_p1;
    sc_signal< sc_lv<2> > add_ln700_10_fu_336_p2;
    sc_signal< sc_lv<2> > zext_ln791_7_fu_276_p1;
    sc_signal< sc_lv<2> > add_ln700_11_fu_342_p2;
    sc_signal< sc_lv<3> > zext_ln700_13_fu_348_p1;
    sc_signal< sc_lv<3> > zext_ln700_12_fu_332_p1;
    sc_signal< sc_lv<3> > add_ln700_12_fu_352_p2;
    sc_signal< sc_lv<4> > zext_ln700_14_fu_358_p1;
    sc_signal< sc_lv<4> > add_ln700_8_fu_320_p2;
    sc_signal< sc_lv<4> > add_ln700_13_fu_362_p2;
    sc_signal< sc_lv<1> > p_Result_14_fu_372_p3;
    sc_signal< sc_lv<1> > p_Result_15_fu_384_p3;
    sc_signal< sc_lv<1> > p_Result_16_fu_396_p3;
    sc_signal< sc_lv<1> > p_Result_17_fu_408_p3;
    sc_signal< sc_lv<1> > p_Result_18_fu_420_p3;
    sc_signal< sc_lv<1> > p_Result_19_fu_432_p3;
    sc_signal< sc_lv<1> > p_Result_20_fu_444_p3;
    sc_signal< sc_lv<1> > p_Result_21_fu_456_p3;
    sc_signal< sc_lv<1> > p_Result_22_fu_468_p3;
    sc_signal< sc_lv<1> > p_Result_23_fu_480_p3;
    sc_signal< sc_lv<1> > p_Result_24_fu_492_p3;
    sc_signal< sc_lv<1> > p_Result_25_fu_504_p3;
    sc_signal< sc_lv<1> > p_Result_26_fu_516_p3;
    sc_signal< sc_lv<1> > p_Result_27_fu_528_p3;
    sc_signal< sc_lv<1> > p_Result_28_fu_540_p3;
    sc_signal< sc_lv<1> > p_Result_29_fu_552_p3;
    sc_signal< sc_lv<5> > zext_ln700_15_fu_368_p1;
    sc_signal< sc_lv<5> > zext_ln700_16_fu_380_p1;
    sc_signal< sc_lv<2> > zext_ln791_9_fu_392_p1;
    sc_signal< sc_lv<2> > zext_ln791_10_fu_404_p1;
    sc_signal< sc_lv<2> > add_ln700_15_fu_570_p2;
    sc_signal< sc_lv<5> > zext_ln700_18_fu_576_p1;
    sc_signal< sc_lv<5> > add_ln700_14_fu_564_p2;
    sc_signal< sc_lv<2> > zext_ln791_11_fu_416_p1;
    sc_signal< sc_lv<2> > zext_ln791_12_fu_428_p1;
    sc_signal< sc_lv<2> > add_ln700_17_fu_586_p2;
    sc_signal< sc_lv<2> > zext_ln791_13_fu_440_p1;
    sc_signal< sc_lv<2> > zext_ln791_14_fu_452_p1;
    sc_signal< sc_lv<2> > add_ln700_18_fu_596_p2;
    sc_signal< sc_lv<3> > zext_ln700_20_fu_602_p1;
    sc_signal< sc_lv<3> > zext_ln700_19_fu_592_p1;
    sc_signal< sc_lv<3> > add_ln700_19_fu_606_p2;
    sc_signal< sc_lv<5> > zext_ln700_21_fu_612_p1;
    sc_signal< sc_lv<5> > add_ln700_16_fu_580_p2;
    sc_signal< sc_lv<2> > zext_ln791_15_fu_464_p1;
    sc_signal< sc_lv<2> > zext_ln791_16_fu_476_p1;
    sc_signal< sc_lv<2> > add_ln700_21_fu_622_p2;
    sc_signal< sc_lv<2> > zext_ln791_17_fu_488_p1;
    sc_signal< sc_lv<2> > zext_ln791_18_fu_500_p1;
    sc_signal< sc_lv<2> > add_ln700_22_fu_632_p2;
    sc_signal< sc_lv<3> > zext_ln700_23_fu_638_p1;
    sc_signal< sc_lv<3> > zext_ln700_22_fu_628_p1;
    sc_signal< sc_lv<3> > add_ln700_23_fu_642_p2;
    sc_signal< sc_lv<2> > zext_ln791_19_fu_512_p1;
    sc_signal< sc_lv<2> > zext_ln791_20_fu_524_p1;
    sc_signal< sc_lv<2> > add_ln700_24_fu_652_p2;
    sc_signal< sc_lv<2> > zext_ln791_22_fu_548_p1;
    sc_signal< sc_lv<2> > zext_ln700_17_fu_560_p1;
    sc_signal< sc_lv<2> > add_ln700_25_fu_662_p2;
    sc_signal< sc_lv<2> > zext_ln791_21_fu_536_p1;
    sc_signal< sc_lv<2> > add_ln700_26_fu_668_p2;
    sc_signal< sc_lv<3> > zext_ln700_26_fu_674_p1;
    sc_signal< sc_lv<3> > zext_ln700_25_fu_658_p1;
    sc_signal< sc_lv<3> > add_ln700_27_fu_678_p2;
    sc_signal< sc_lv<4> > zext_ln700_27_fu_684_p1;
    sc_signal< sc_lv<4> > zext_ln700_24_fu_648_p1;
    sc_signal< sc_lv<4> > add_ln700_28_fu_688_p2;
    sc_signal< sc_lv<5> > zext_ln700_28_fu_694_p1;
    sc_signal< sc_lv<5> > add_ln700_20_fu_616_p2;
    sc_signal< sc_lv<5> > add_ln700_29_fu_698_p2;
    sc_signal< sc_lv<1> > p_Result_30_fu_708_p3;
    sc_signal< sc_lv<6> > zext_ln700_29_fu_704_p1;
    sc_signal< sc_lv<6> > zext_ln700_30_fu_716_p1;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_1A;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_add_ln700_10_fu_336_p2();
    void thread_add_ln700_11_fu_342_p2();
    void thread_add_ln700_12_fu_352_p2();
    void thread_add_ln700_13_fu_362_p2();
    void thread_add_ln700_14_fu_564_p2();
    void thread_add_ln700_15_fu_570_p2();
    void thread_add_ln700_16_fu_580_p2();
    void thread_add_ln700_17_fu_586_p2();
    void thread_add_ln700_18_fu_596_p2();
    void thread_add_ln700_19_fu_606_p2();
    void thread_add_ln700_1_fu_112_p2();
    void thread_add_ln700_20_fu_616_p2();
    void thread_add_ln700_21_fu_622_p2();
    void thread_add_ln700_22_fu_632_p2();
    void thread_add_ln700_23_fu_642_p2();
    void thread_add_ln700_24_fu_652_p2();
    void thread_add_ln700_25_fu_662_p2();
    void thread_add_ln700_26_fu_668_p2();
    void thread_add_ln700_27_fu_678_p2();
    void thread_add_ln700_28_fu_688_p2();
    void thread_add_ln700_29_fu_698_p2();
    void thread_add_ln700_2_fu_176_p2();
    void thread_add_ln700_3_fu_182_p2();
    void thread_add_ln700_4_fu_188_p2();
    void thread_add_ln700_5_fu_198_p2();
    void thread_add_ln700_6_fu_304_p2();
    void thread_add_ln700_7_fu_310_p2();
    void thread_add_ln700_8_fu_320_p2();
    void thread_add_ln700_9_fu_326_p2();
    void thread_add_ln700_fu_118_p2();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_p_Result_10_fu_256_p3();
    void thread_p_Result_11_fu_268_p3();
    void thread_p_Result_12_fu_280_p3();
    void thread_p_Result_13_fu_292_p3();
    void thread_p_Result_14_fu_372_p3();
    void thread_p_Result_15_fu_384_p3();
    void thread_p_Result_16_fu_396_p3();
    void thread_p_Result_17_fu_408_p3();
    void thread_p_Result_18_fu_420_p3();
    void thread_p_Result_19_fu_432_p3();
    void thread_p_Result_1_fu_88_p3();
    void thread_p_Result_20_fu_444_p3();
    void thread_p_Result_21_fu_456_p3();
    void thread_p_Result_22_fu_468_p3();
    void thread_p_Result_23_fu_480_p3();
    void thread_p_Result_24_fu_492_p3();
    void thread_p_Result_25_fu_504_p3();
    void thread_p_Result_26_fu_516_p3();
    void thread_p_Result_27_fu_528_p3();
    void thread_p_Result_28_fu_540_p3();
    void thread_p_Result_29_fu_552_p3();
    void thread_p_Result_2_fu_100_p3();
    void thread_p_Result_30_fu_708_p3();
    void thread_p_Result_3_fu_128_p3();
    void thread_p_Result_4_fu_140_p3();
    void thread_p_Result_5_fu_152_p3();
    void thread_p_Result_6_fu_164_p3();
    void thread_p_Result_7_fu_208_p3();
    void thread_p_Result_8_fu_220_p3();
    void thread_p_Result_9_fu_232_p3();
    void thread_p_Result_s_13_fu_244_p3();
    void thread_p_Result_s_fu_76_p3();
    void thread_zext_ln700_10_fu_300_p1();
    void thread_zext_ln700_11_fu_316_p1();
    void thread_zext_ln700_12_fu_332_p1();
    void thread_zext_ln700_13_fu_348_p1();
    void thread_zext_ln700_14_fu_358_p1();
    void thread_zext_ln700_15_fu_368_p1();
    void thread_zext_ln700_16_fu_380_p1();
    void thread_zext_ln700_17_fu_560_p1();
    void thread_zext_ln700_18_fu_576_p1();
    void thread_zext_ln700_19_fu_592_p1();
    void thread_zext_ln700_20_fu_602_p1();
    void thread_zext_ln700_21_fu_612_p1();
    void thread_zext_ln700_22_fu_628_p1();
    void thread_zext_ln700_23_fu_638_p1();
    void thread_zext_ln700_24_fu_648_p1();
    void thread_zext_ln700_25_fu_658_p1();
    void thread_zext_ln700_26_fu_674_p1();
    void thread_zext_ln700_27_fu_684_p1();
    void thread_zext_ln700_28_fu_694_p1();
    void thread_zext_ln700_29_fu_704_p1();
    void thread_zext_ln700_30_fu_716_p1();
    void thread_zext_ln700_3_fu_108_p1();
    void thread_zext_ln700_4_fu_124_p1();
    void thread_zext_ln700_5_fu_136_p1();
    void thread_zext_ln700_6_fu_172_p1();
    void thread_zext_ln700_7_fu_194_p1();
    void thread_zext_ln700_8_fu_204_p1();
    void thread_zext_ln700_9_fu_216_p1();
    void thread_zext_ln700_fu_96_p1();
    void thread_zext_ln791_10_fu_404_p1();
    void thread_zext_ln791_11_fu_416_p1();
    void thread_zext_ln791_12_fu_428_p1();
    void thread_zext_ln791_13_fu_440_p1();
    void thread_zext_ln791_14_fu_452_p1();
    void thread_zext_ln791_15_fu_464_p1();
    void thread_zext_ln791_16_fu_476_p1();
    void thread_zext_ln791_17_fu_488_p1();
    void thread_zext_ln791_18_fu_500_p1();
    void thread_zext_ln791_19_fu_512_p1();
    void thread_zext_ln791_1_fu_148_p1();
    void thread_zext_ln791_20_fu_524_p1();
    void thread_zext_ln791_21_fu_536_p1();
    void thread_zext_ln791_22_fu_548_p1();
    void thread_zext_ln791_2_fu_160_p1();
    void thread_zext_ln791_3_fu_228_p1();
    void thread_zext_ln791_4_fu_240_p1();
    void thread_zext_ln791_5_fu_252_p1();
    void thread_zext_ln791_6_fu_264_p1();
    void thread_zext_ln791_7_fu_276_p1();
    void thread_zext_ln791_8_fu_288_p1();
    void thread_zext_ln791_9_fu_392_p1();
    void thread_zext_ln791_fu_84_p1();
};

}

using namespace ap_rtl;

#endif
