// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _tancalc_tancalc_HH_
#define _tancalc_tancalc_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "tancalc_dataflow_parent_loop_proc.h"
#include "tancalc_data_read_1.h"
#include "tancalc_tancalc_control_s_axi.h"
#include "tancalc_tancalc_gmem0_m_axi.h"
#include "tancalc_tancalc_gmem1_m_axi.h"

namespace ap_rtl {

template<unsigned int C_M_AXI_GMEM0_ADDR_WIDTH = 64,
         unsigned int C_M_AXI_GMEM0_ID_WIDTH = 1,
         unsigned int C_M_AXI_GMEM0_AWUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM0_DATA_WIDTH = 512,
         unsigned int C_M_AXI_GMEM0_WUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM0_ARUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM0_RUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM0_BUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_ADDR_WIDTH = 64,
         unsigned int C_M_AXI_GMEM1_ID_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_AWUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_DATA_WIDTH = 512,
         unsigned int C_M_AXI_GMEM1_WUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_ARUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_RUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_BUSER_WIDTH = 1,
         unsigned int C_S_AXI_CONTROL_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_CONTROL_DATA_WIDTH = 32>
struct tancalc_tancalc : public sc_module {
    // Port declarations 110
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > m_axi_gmem0_AWVALID;
    sc_in< sc_logic > m_axi_gmem0_AWREADY;
    sc_out< sc_uint<C_M_AXI_GMEM0_ADDR_WIDTH> > m_axi_gmem0_AWADDR;
    sc_out< sc_uint<C_M_AXI_GMEM0_ID_WIDTH> > m_axi_gmem0_AWID;
    sc_out< sc_lv<8> > m_axi_gmem0_AWLEN;
    sc_out< sc_lv<3> > m_axi_gmem0_AWSIZE;
    sc_out< sc_lv<2> > m_axi_gmem0_AWBURST;
    sc_out< sc_lv<2> > m_axi_gmem0_AWLOCK;
    sc_out< sc_lv<4> > m_axi_gmem0_AWCACHE;
    sc_out< sc_lv<3> > m_axi_gmem0_AWPROT;
    sc_out< sc_lv<4> > m_axi_gmem0_AWQOS;
    sc_out< sc_lv<4> > m_axi_gmem0_AWREGION;
    sc_out< sc_uint<C_M_AXI_GMEM0_AWUSER_WIDTH> > m_axi_gmem0_AWUSER;
    sc_out< sc_logic > m_axi_gmem0_WVALID;
    sc_in< sc_logic > m_axi_gmem0_WREADY;
    sc_out< sc_uint<C_M_AXI_GMEM0_DATA_WIDTH> > m_axi_gmem0_WDATA;
    sc_out< sc_uint<C_M_AXI_GMEM0_DATA_WIDTH/8> > m_axi_gmem0_WSTRB;
    sc_out< sc_logic > m_axi_gmem0_WLAST;
    sc_out< sc_uint<C_M_AXI_GMEM0_ID_WIDTH> > m_axi_gmem0_WID;
    sc_out< sc_uint<C_M_AXI_GMEM0_WUSER_WIDTH> > m_axi_gmem0_WUSER;
    sc_out< sc_logic > m_axi_gmem0_ARVALID;
    sc_in< sc_logic > m_axi_gmem0_ARREADY;
    sc_out< sc_uint<C_M_AXI_GMEM0_ADDR_WIDTH> > m_axi_gmem0_ARADDR;
    sc_out< sc_uint<C_M_AXI_GMEM0_ID_WIDTH> > m_axi_gmem0_ARID;
    sc_out< sc_lv<8> > m_axi_gmem0_ARLEN;
    sc_out< sc_lv<3> > m_axi_gmem0_ARSIZE;
    sc_out< sc_lv<2> > m_axi_gmem0_ARBURST;
    sc_out< sc_lv<2> > m_axi_gmem0_ARLOCK;
    sc_out< sc_lv<4> > m_axi_gmem0_ARCACHE;
    sc_out< sc_lv<3> > m_axi_gmem0_ARPROT;
    sc_out< sc_lv<4> > m_axi_gmem0_ARQOS;
    sc_out< sc_lv<4> > m_axi_gmem0_ARREGION;
    sc_out< sc_uint<C_M_AXI_GMEM0_ARUSER_WIDTH> > m_axi_gmem0_ARUSER;
    sc_in< sc_logic > m_axi_gmem0_RVALID;
    sc_out< sc_logic > m_axi_gmem0_RREADY;
    sc_in< sc_uint<C_M_AXI_GMEM0_DATA_WIDTH> > m_axi_gmem0_RDATA;
    sc_in< sc_logic > m_axi_gmem0_RLAST;
    sc_in< sc_uint<C_M_AXI_GMEM0_ID_WIDTH> > m_axi_gmem0_RID;
    sc_in< sc_uint<C_M_AXI_GMEM0_RUSER_WIDTH> > m_axi_gmem0_RUSER;
    sc_in< sc_lv<2> > m_axi_gmem0_RRESP;
    sc_in< sc_logic > m_axi_gmem0_BVALID;
    sc_out< sc_logic > m_axi_gmem0_BREADY;
    sc_in< sc_lv<2> > m_axi_gmem0_BRESP;
    sc_in< sc_uint<C_M_AXI_GMEM0_ID_WIDTH> > m_axi_gmem0_BID;
    sc_in< sc_uint<C_M_AXI_GMEM0_BUSER_WIDTH> > m_axi_gmem0_BUSER;
    sc_out< sc_logic > m_axi_gmem1_AWVALID;
    sc_in< sc_logic > m_axi_gmem1_AWREADY;
    sc_out< sc_uint<C_M_AXI_GMEM1_ADDR_WIDTH> > m_axi_gmem1_AWADDR;
    sc_out< sc_uint<C_M_AXI_GMEM1_ID_WIDTH> > m_axi_gmem1_AWID;
    sc_out< sc_lv<8> > m_axi_gmem1_AWLEN;
    sc_out< sc_lv<3> > m_axi_gmem1_AWSIZE;
    sc_out< sc_lv<2> > m_axi_gmem1_AWBURST;
    sc_out< sc_lv<2> > m_axi_gmem1_AWLOCK;
    sc_out< sc_lv<4> > m_axi_gmem1_AWCACHE;
    sc_out< sc_lv<3> > m_axi_gmem1_AWPROT;
    sc_out< sc_lv<4> > m_axi_gmem1_AWQOS;
    sc_out< sc_lv<4> > m_axi_gmem1_AWREGION;
    sc_out< sc_uint<C_M_AXI_GMEM1_AWUSER_WIDTH> > m_axi_gmem1_AWUSER;
    sc_out< sc_logic > m_axi_gmem1_WVALID;
    sc_in< sc_logic > m_axi_gmem1_WREADY;
    sc_out< sc_uint<C_M_AXI_GMEM1_DATA_WIDTH> > m_axi_gmem1_WDATA;
    sc_out< sc_uint<C_M_AXI_GMEM1_DATA_WIDTH/8> > m_axi_gmem1_WSTRB;
    sc_out< sc_logic > m_axi_gmem1_WLAST;
    sc_out< sc_uint<C_M_AXI_GMEM1_ID_WIDTH> > m_axi_gmem1_WID;
    sc_out< sc_uint<C_M_AXI_GMEM1_WUSER_WIDTH> > m_axi_gmem1_WUSER;
    sc_out< sc_logic > m_axi_gmem1_ARVALID;
    sc_in< sc_logic > m_axi_gmem1_ARREADY;
    sc_out< sc_uint<C_M_AXI_GMEM1_ADDR_WIDTH> > m_axi_gmem1_ARADDR;
    sc_out< sc_uint<C_M_AXI_GMEM1_ID_WIDTH> > m_axi_gmem1_ARID;
    sc_out< sc_lv<8> > m_axi_gmem1_ARLEN;
    sc_out< sc_lv<3> > m_axi_gmem1_ARSIZE;
    sc_out< sc_lv<2> > m_axi_gmem1_ARBURST;
    sc_out< sc_lv<2> > m_axi_gmem1_ARLOCK;
    sc_out< sc_lv<4> > m_axi_gmem1_ARCACHE;
    sc_out< sc_lv<3> > m_axi_gmem1_ARPROT;
    sc_out< sc_lv<4> > m_axi_gmem1_ARQOS;
    sc_out< sc_lv<4> > m_axi_gmem1_ARREGION;
    sc_out< sc_uint<C_M_AXI_GMEM1_ARUSER_WIDTH> > m_axi_gmem1_ARUSER;
    sc_in< sc_logic > m_axi_gmem1_RVALID;
    sc_out< sc_logic > m_axi_gmem1_RREADY;
    sc_in< sc_uint<C_M_AXI_GMEM1_DATA_WIDTH> > m_axi_gmem1_RDATA;
    sc_in< sc_logic > m_axi_gmem1_RLAST;
    sc_in< sc_uint<C_M_AXI_GMEM1_ID_WIDTH> > m_axi_gmem1_RID;
    sc_in< sc_uint<C_M_AXI_GMEM1_RUSER_WIDTH> > m_axi_gmem1_RUSER;
    sc_in< sc_lv<2> > m_axi_gmem1_RRESP;
    sc_in< sc_logic > m_axi_gmem1_BVALID;
    sc_out< sc_logic > m_axi_gmem1_BREADY;
    sc_in< sc_lv<2> > m_axi_gmem1_BRESP;
    sc_in< sc_uint<C_M_AXI_GMEM1_ID_WIDTH> > m_axi_gmem1_BID;
    sc_in< sc_uint<C_M_AXI_GMEM1_BUSER_WIDTH> > m_axi_gmem1_BUSER;
    sc_in< sc_logic > s_axi_control_AWVALID;
    sc_out< sc_logic > s_axi_control_AWREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_ADDR_WIDTH> > s_axi_control_AWADDR;
    sc_in< sc_logic > s_axi_control_WVALID;
    sc_out< sc_logic > s_axi_control_WREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_DATA_WIDTH> > s_axi_control_WDATA;
    sc_in< sc_uint<C_S_AXI_CONTROL_DATA_WIDTH/8> > s_axi_control_WSTRB;
    sc_in< sc_logic > s_axi_control_ARVALID;
    sc_out< sc_logic > s_axi_control_ARREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_ADDR_WIDTH> > s_axi_control_ARADDR;
    sc_out< sc_logic > s_axi_control_RVALID;
    sc_in< sc_logic > s_axi_control_RREADY;
    sc_out< sc_uint<C_S_AXI_CONTROL_DATA_WIDTH> > s_axi_control_RDATA;
    sc_out< sc_lv<2> > s_axi_control_RRESP;
    sc_out< sc_logic > s_axi_control_BVALID;
    sc_in< sc_logic > s_axi_control_BREADY;
    sc_out< sc_lv<2> > s_axi_control_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_logic > ap_var_for_const1;
    sc_signal< sc_lv<32> > ap_var_for_const4;
    sc_signal< sc_lv<1> > ap_var_for_const3;
    sc_signal< sc_lv<3> > ap_var_for_const5;
    sc_signal< sc_lv<4> > ap_var_for_const7;
    sc_signal< sc_lv<64> > ap_var_for_const2;
    sc_signal< sc_lv<2> > ap_var_for_const6;
    sc_signal< sc_lv<512> > ap_var_for_const8;


    // Module declarations
    tancalc_tancalc(sc_module_name name);
    SC_HAS_PROCESS(tancalc_tancalc);

    ~tancalc_tancalc();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    tancalc_tancalc_control_s_axi<C_S_AXI_CONTROL_ADDR_WIDTH,C_S_AXI_CONTROL_DATA_WIDTH>* tancalc_control_s_axi_U;
    tancalc_tancalc_gmem0_m_axi<0,512,64,5,16,16,16,16,C_M_AXI_GMEM0_ID_WIDTH,C_M_AXI_GMEM0_ADDR_WIDTH,C_M_AXI_GMEM0_DATA_WIDTH,C_M_AXI_GMEM0_AWUSER_WIDTH,C_M_AXI_GMEM0_ARUSER_WIDTH,C_M_AXI_GMEM0_WUSER_WIDTH,C_M_AXI_GMEM0_RUSER_WIDTH,C_M_AXI_GMEM0_BUSER_WIDTH,C_M_AXI_GMEM0_USER_VALUE,C_M_AXI_GMEM0_PROT_VALUE,C_M_AXI_GMEM0_CACHE_VALUE>* tancalc_gmem0_m_axi_U;
    tancalc_tancalc_gmem1_m_axi<0,512,64,5,16,16,16,16,C_M_AXI_GMEM1_ID_WIDTH,C_M_AXI_GMEM1_ADDR_WIDTH,C_M_AXI_GMEM1_DATA_WIDTH,C_M_AXI_GMEM1_AWUSER_WIDTH,C_M_AXI_GMEM1_ARUSER_WIDTH,C_M_AXI_GMEM1_WUSER_WIDTH,C_M_AXI_GMEM1_RUSER_WIDTH,C_M_AXI_GMEM1_BUSER_WIDTH,C_M_AXI_GMEM1_USER_VALUE,C_M_AXI_GMEM1_PROT_VALUE,C_M_AXI_GMEM1_CACHE_VALUE>* tancalc_gmem1_m_axi_U;
    tancalc_dataflow_parent_loop_proc* grp_dataflow_parent_loop_proc_fu_222;
    tancalc_data_read_1* grp_data_read_1_fu_266;
    sc_signal< sc_logic > ap_rst_reg_2;
    sc_signal< sc_logic > ap_rst_reg_1;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<64> > input_V;
    sc_signal< sc_lv<64> > output_V;
    sc_signal< sc_logic > gmem0_AWREADY;
    sc_signal< sc_logic > gmem0_WREADY;
    sc_signal< sc_logic > gmem0_ARVALID;
    sc_signal< sc_logic > gmem0_ARREADY;
    sc_signal< sc_lv<64> > gmem0_ARADDR;
    sc_signal< sc_lv<1> > gmem0_ARID;
    sc_signal< sc_lv<32> > gmem0_ARLEN;
    sc_signal< sc_lv<3> > gmem0_ARSIZE;
    sc_signal< sc_lv<2> > gmem0_ARBURST;
    sc_signal< sc_lv<2> > gmem0_ARLOCK;
    sc_signal< sc_lv<4> > gmem0_ARCACHE;
    sc_signal< sc_lv<3> > gmem0_ARPROT;
    sc_signal< sc_lv<4> > gmem0_ARQOS;
    sc_signal< sc_lv<4> > gmem0_ARREGION;
    sc_signal< sc_lv<1> > gmem0_ARUSER;
    sc_signal< sc_logic > gmem0_RVALID;
    sc_signal< sc_logic > gmem0_RREADY;
    sc_signal< sc_lv<512> > gmem0_RDATA;
    sc_signal< sc_logic > gmem0_RLAST;
    sc_signal< sc_lv<1> > gmem0_RID;
    sc_signal< sc_lv<1> > gmem0_RUSER;
    sc_signal< sc_lv<2> > gmem0_RRESP;
    sc_signal< sc_logic > gmem0_BVALID;
    sc_signal< sc_lv<2> > gmem0_BRESP;
    sc_signal< sc_lv<1> > gmem0_BID;
    sc_signal< sc_lv<1> > gmem0_BUSER;
    sc_signal< sc_logic > gmem1_AWVALID;
    sc_signal< sc_logic > gmem1_AWREADY;
    sc_signal< sc_logic > gmem1_WVALID;
    sc_signal< sc_logic > gmem1_WREADY;
    sc_signal< sc_logic > gmem1_ARREADY;
    sc_signal< sc_logic > gmem1_RVALID;
    sc_signal< sc_lv<512> > gmem1_RDATA;
    sc_signal< sc_logic > gmem1_RLAST;
    sc_signal< sc_lv<1> > gmem1_RID;
    sc_signal< sc_lv<1> > gmem1_RUSER;
    sc_signal< sc_lv<2> > gmem1_RRESP;
    sc_signal< sc_logic > gmem1_BVALID;
    sc_signal< sc_logic > gmem1_BREADY;
    sc_signal< sc_lv<2> > gmem1_BRESP;
    sc_signal< sc_lv<1> > gmem1_BID;
    sc_signal< sc_lv<1> > gmem1_BUSER;
    sc_signal< sc_lv<58> > output_V3_reg_959;
    sc_signal< sc_lv<58> > input_V1_reg_964;
    sc_signal< sc_lv<3> > cmpr_chunk_num_fu_332_p2;
    sc_signal< sc_lv<3> > cmpr_chunk_num_reg_973;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln92_fu_326_p2;
    sc_signal< sc_lv<6> > shl_ln_fu_470_p3;
    sc_signal< sc_lv<6> > shl_ln_reg_1138;
    sc_signal< sc_lv<1024> > cmpr_local_0_V_reg_1143;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > grp_data_read_1_fu_266_ap_ready;
    sc_signal< sc_logic > grp_data_read_1_fu_266_ap_done;
    sc_signal< sc_lv<1024> > cmpr_local_1_V_reg_1148;
    sc_signal< sc_lv<1024> > cmpr_local_2_V_reg_1153;
    sc_signal< sc_lv<1024> > cmpr_local_3_V_reg_1158;
    sc_signal< sc_lv<1024> > cmpr_local_4_V_reg_1163;
    sc_signal< sc_lv<1024> > cmpr_local_5_V_reg_1168;
    sc_signal< sc_lv<1024> > cmpr_local_6_V_reg_1173;
    sc_signal< sc_lv<1024> > cmpr_local_7_V_reg_1178;
    sc_signal< sc_lv<1024> > cmpr_local_8_V_reg_1183;
    sc_signal< sc_lv<1024> > cmpr_local_9_V_reg_1188;
    sc_signal< sc_lv<1024> > cmpr_local_10_V_reg_1193;
    sc_signal< sc_lv<1024> > cmpr_local_11_V_reg_1198;
    sc_signal< sc_lv<1024> > cmpr_local_12_V_reg_1203;
    sc_signal< sc_lv<1024> > cmpr_local_13_V_reg_1208;
    sc_signal< sc_lv<1024> > cmpr_local_14_V_reg_1213;
    sc_signal< sc_lv<1024> > cmpr_local_15_V_reg_1218;
    sc_signal< sc_lv<11> > cmprpop_local_0_V_reg_1223;
    sc_signal< sc_lv<11> > cmprpop_local_1_V_reg_1228;
    sc_signal< sc_lv<11> > cmprpop_local_2_V_reg_1233;
    sc_signal< sc_lv<11> > cmprpop_local_3_V_reg_1238;
    sc_signal< sc_lv<11> > cmprpop_local_4_V_reg_1243;
    sc_signal< sc_lv<11> > cmprpop_local_5_V_reg_1248;
    sc_signal< sc_lv<11> > cmprpop_local_6_V_reg_1253;
    sc_signal< sc_lv<11> > cmprpop_local_7_V_reg_1258;
    sc_signal< sc_lv<11> > cmprpop_local_8_V_reg_1263;
    sc_signal< sc_lv<11> > cmprpop_local_9_V_reg_1268;
    sc_signal< sc_lv<11> > cmprpop_local_10_V_reg_1273;
    sc_signal< sc_lv<11> > cmprpop_local_11_V_reg_1278;
    sc_signal< sc_lv<11> > cmprpop_local_12_V_reg_1283;
    sc_signal< sc_lv<11> > cmprpop_local_13_V_reg_1288;
    sc_signal< sc_lv<11> > cmprpop_local_14_V_reg_1293;
    sc_signal< sc_lv<10> > cmprpop_local_15_V_reg_1298;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWVALID;
    sc_signal< sc_lv<64> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWADDR;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWID;
    sc_signal< sc_lv<32> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWLEN;
    sc_signal< sc_lv<3> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWSIZE;
    sc_signal< sc_lv<2> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWBURST;
    sc_signal< sc_lv<2> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWLOCK;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWCACHE;
    sc_signal< sc_lv<3> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWPROT;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWQOS;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWREGION;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_AWUSER;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_WVALID;
    sc_signal< sc_lv<512> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_WDATA;
    sc_signal< sc_lv<64> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_WSTRB;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_WLAST;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_WID;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_WUSER;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARVALID;
    sc_signal< sc_lv<64> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARADDR;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARID;
    sc_signal< sc_lv<32> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARLEN;
    sc_signal< sc_lv<3> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARSIZE;
    sc_signal< sc_lv<2> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARBURST;
    sc_signal< sc_lv<2> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARLOCK;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARCACHE;
    sc_signal< sc_lv<3> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARPROT;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARQOS;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARREGION;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_ARUSER;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_RREADY;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_input_V_BREADY;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWVALID;
    sc_signal< sc_lv<64> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWADDR;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWID;
    sc_signal< sc_lv<32> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWLEN;
    sc_signal< sc_lv<3> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWSIZE;
    sc_signal< sc_lv<2> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWBURST;
    sc_signal< sc_lv<2> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWLOCK;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWCACHE;
    sc_signal< sc_lv<3> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWPROT;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWQOS;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWREGION;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_AWUSER;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_WVALID;
    sc_signal< sc_lv<512> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_WDATA;
    sc_signal< sc_lv<64> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_WSTRB;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_WLAST;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_WID;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_WUSER;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARVALID;
    sc_signal< sc_lv<64> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARADDR;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARID;
    sc_signal< sc_lv<32> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARLEN;
    sc_signal< sc_lv<3> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARSIZE;
    sc_signal< sc_lv<2> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARBURST;
    sc_signal< sc_lv<2> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARLOCK;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARCACHE;
    sc_signal< sc_lv<3> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARPROT;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARQOS;
    sc_signal< sc_lv<4> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARREGION;
    sc_signal< sc_lv<1> > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_ARUSER;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_RREADY;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_m_axi_output_V_BREADY;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_ap_start;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_ap_done;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_ap_ready;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_ap_idle;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_ap_continue;
    sc_signal< sc_logic > grp_data_read_1_fu_266_ap_start;
    sc_signal< sc_logic > grp_data_read_1_fu_266_ap_idle;
    sc_signal< sc_logic > grp_data_read_1_fu_266_m_axi_input_V_AWVALID;
    sc_signal< sc_lv<64> > grp_data_read_1_fu_266_m_axi_input_V_AWADDR;
    sc_signal< sc_lv<1> > grp_data_read_1_fu_266_m_axi_input_V_AWID;
    sc_signal< sc_lv<32> > grp_data_read_1_fu_266_m_axi_input_V_AWLEN;
    sc_signal< sc_lv<3> > grp_data_read_1_fu_266_m_axi_input_V_AWSIZE;
    sc_signal< sc_lv<2> > grp_data_read_1_fu_266_m_axi_input_V_AWBURST;
    sc_signal< sc_lv<2> > grp_data_read_1_fu_266_m_axi_input_V_AWLOCK;
    sc_signal< sc_lv<4> > grp_data_read_1_fu_266_m_axi_input_V_AWCACHE;
    sc_signal< sc_lv<3> > grp_data_read_1_fu_266_m_axi_input_V_AWPROT;
    sc_signal< sc_lv<4> > grp_data_read_1_fu_266_m_axi_input_V_AWQOS;
    sc_signal< sc_lv<4> > grp_data_read_1_fu_266_m_axi_input_V_AWREGION;
    sc_signal< sc_lv<1> > grp_data_read_1_fu_266_m_axi_input_V_AWUSER;
    sc_signal< sc_logic > grp_data_read_1_fu_266_m_axi_input_V_WVALID;
    sc_signal< sc_lv<512> > grp_data_read_1_fu_266_m_axi_input_V_WDATA;
    sc_signal< sc_lv<64> > grp_data_read_1_fu_266_m_axi_input_V_WSTRB;
    sc_signal< sc_logic > grp_data_read_1_fu_266_m_axi_input_V_WLAST;
    sc_signal< sc_lv<1> > grp_data_read_1_fu_266_m_axi_input_V_WID;
    sc_signal< sc_lv<1> > grp_data_read_1_fu_266_m_axi_input_V_WUSER;
    sc_signal< sc_logic > grp_data_read_1_fu_266_m_axi_input_V_ARVALID;
    sc_signal< sc_lv<64> > grp_data_read_1_fu_266_m_axi_input_V_ARADDR;
    sc_signal< sc_lv<1> > grp_data_read_1_fu_266_m_axi_input_V_ARID;
    sc_signal< sc_lv<32> > grp_data_read_1_fu_266_m_axi_input_V_ARLEN;
    sc_signal< sc_lv<3> > grp_data_read_1_fu_266_m_axi_input_V_ARSIZE;
    sc_signal< sc_lv<2> > grp_data_read_1_fu_266_m_axi_input_V_ARBURST;
    sc_signal< sc_lv<2> > grp_data_read_1_fu_266_m_axi_input_V_ARLOCK;
    sc_signal< sc_lv<4> > grp_data_read_1_fu_266_m_axi_input_V_ARCACHE;
    sc_signal< sc_lv<3> > grp_data_read_1_fu_266_m_axi_input_V_ARPROT;
    sc_signal< sc_lv<4> > grp_data_read_1_fu_266_m_axi_input_V_ARQOS;
    sc_signal< sc_lv<4> > grp_data_read_1_fu_266_m_axi_input_V_ARREGION;
    sc_signal< sc_lv<1> > grp_data_read_1_fu_266_m_axi_input_V_ARUSER;
    sc_signal< sc_logic > grp_data_read_1_fu_266_m_axi_input_V_RREADY;
    sc_signal< sc_logic > grp_data_read_1_fu_266_m_axi_input_V_BREADY;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_0;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_1;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_2;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_3;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_4;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_5;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_6;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_7;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_8;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_9;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_10;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_11;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_12;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_13;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_14;
    sc_signal< sc_lv<1024> > grp_data_read_1_fu_266_ap_return_15;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_16;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_17;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_18;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_19;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_20;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_21;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_22;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_23;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_24;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_25;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_26;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_27;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_28;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_29;
    sc_signal< sc_lv<11> > grp_data_read_1_fu_266_ap_return_30;
    sc_signal< sc_lv<10> > grp_data_read_1_fu_266_ap_return_31;
    sc_signal< sc_lv<3> > cmpr_chunk_num_0_i_reg_210;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_sync_grp_dataflow_parent_loop_proc_fu_222_ap_ready;
    sc_signal< sc_logic > ap_sync_grp_dataflow_parent_loop_proc_fu_222_ap_done;
    sc_signal< bool > ap_block_state5_on_subcall_done;
    sc_signal< sc_logic > grp_dataflow_parent_loop_proc_fu_222_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_sync_reg_grp_dataflow_parent_loop_proc_fu_222_ap_ready;
    sc_signal< sc_logic > ap_sync_reg_grp_dataflow_parent_loop_proc_fu_222_ap_done;
    sc_signal< sc_logic > grp_data_read_1_fu_266_ap_start_reg;
    sc_signal< sc_lv<1024> > cmpr_local_0_V_1_fu_70;
    sc_signal< sc_lv<1024> > cmpr_local_1_V_1_fu_74;
    sc_signal< sc_lv<1024> > cmpr_local_2_V_1_fu_78;
    sc_signal< sc_lv<1024> > cmpr_local_3_V_1_fu_82;
    sc_signal< sc_lv<1024> > cmpr_local_4_V_1_fu_86;
    sc_signal< sc_lv<1024> > cmpr_local_5_V_1_fu_90;
    sc_signal< sc_lv<1024> > cmpr_local_6_V_1_fu_94;
    sc_signal< sc_lv<1024> > cmpr_local_7_V_1_fu_98;
    sc_signal< sc_lv<1024> > cmpr_local_8_V_1_fu_102;
    sc_signal< sc_lv<1024> > cmpr_local_9_V_1_fu_106;
    sc_signal< sc_lv<1024> > cmpr_local_10_V_1_fu_110;
    sc_signal< sc_lv<1024> > cmpr_local_11_V_1_fu_114;
    sc_signal< sc_lv<1024> > cmpr_local_12_V_1_fu_118;
    sc_signal< sc_lv<1024> > cmpr_local_13_V_1_fu_122;
    sc_signal< sc_lv<1024> > cmpr_local_14_V_1_fu_126;
    sc_signal< sc_lv<1024> > cmpr_local_15_V_1_fu_130;
    sc_signal< sc_lv<11> > cmprpop_local_0_V_1_fu_134;
    sc_signal< sc_lv<11> > cmprpop_local_1_V_1_fu_138;
    sc_signal< sc_lv<11> > cmprpop_local_2_V_1_fu_142;
    sc_signal< sc_lv<11> > cmprpop_local_3_V_1_fu_146;
    sc_signal< sc_lv<11> > cmprpop_local_4_V_1_fu_150;
    sc_signal< sc_lv<11> > cmprpop_local_5_V_1_fu_154;
    sc_signal< sc_lv<11> > cmprpop_local_6_V_1_fu_158;
    sc_signal< sc_lv<11> > cmprpop_local_7_V_1_fu_162;
    sc_signal< sc_lv<11> > cmprpop_local_8_V_1_fu_166;
    sc_signal< sc_lv<11> > cmprpop_local_9_V_1_fu_170;
    sc_signal< sc_lv<11> > cmprpop_local_10_V_1_fu_174;
    sc_signal< sc_lv<11> > cmprpop_local_11_V_1_fu_178;
    sc_signal< sc_lv<11> > cmprpop_local_12_V_1_fu_182;
    sc_signal< sc_lv<11> > cmprpop_local_13_V_1_fu_186;
    sc_signal< sc_lv<11> > cmprpop_local_14_V_1_fu_190;
    sc_signal< sc_lv<10> > cmprpop_local_15_V_1_fu_194;
    sc_signal< sc_lv<2> > trunc_ln93_fu_466_p1;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_state3;
    static const sc_lv<5> ap_ST_fsm_state4;
    static const sc_lv<5> ap_ST_fsm_state5;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_M_AXI_GMEM0_USER_VALUE;
    static const int C_M_AXI_GMEM0_PROT_VALUE;
    static const int C_M_AXI_GMEM0_CACHE_VALUE;
    static const int C_M_AXI_DATA_WIDTH;
    static const int C_M_AXI_GMEM1_USER_VALUE;
    static const int C_M_AXI_GMEM1_PROT_VALUE;
    static const int C_M_AXI_GMEM1_CACHE_VALUE;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<512> ap_const_lv512_lc_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const4();
    void thread_ap_var_for_const3();
    void thread_ap_var_for_const5();
    void thread_ap_var_for_const7();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const6();
    void thread_ap_var_for_const8();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_state5_on_subcall_done();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_grp_dataflow_parent_loop_proc_fu_222_ap_done();
    void thread_ap_sync_grp_dataflow_parent_loop_proc_fu_222_ap_ready();
    void thread_cmpr_chunk_num_fu_332_p2();
    void thread_gmem0_ARADDR();
    void thread_gmem0_ARBURST();
    void thread_gmem0_ARCACHE();
    void thread_gmem0_ARID();
    void thread_gmem0_ARLEN();
    void thread_gmem0_ARLOCK();
    void thread_gmem0_ARPROT();
    void thread_gmem0_ARQOS();
    void thread_gmem0_ARREGION();
    void thread_gmem0_ARSIZE();
    void thread_gmem0_ARUSER();
    void thread_gmem0_ARVALID();
    void thread_gmem0_RREADY();
    void thread_gmem1_AWVALID();
    void thread_gmem1_BREADY();
    void thread_gmem1_WVALID();
    void thread_grp_data_read_1_fu_266_ap_start();
    void thread_grp_dataflow_parent_loop_proc_fu_222_ap_continue();
    void thread_grp_dataflow_parent_loop_proc_fu_222_ap_start();
    void thread_icmp_ln92_fu_326_p2();
    void thread_shl_ln_fu_470_p3();
    void thread_trunc_ln93_fu_466_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
