// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tancalc_dataflow_parent_loop_proc (
        m_axi_input_V_AWVALID,
        m_axi_input_V_AWREADY,
        m_axi_input_V_AWADDR,
        m_axi_input_V_AWID,
        m_axi_input_V_AWLEN,
        m_axi_input_V_AWSIZE,
        m_axi_input_V_AWBURST,
        m_axi_input_V_AWLOCK,
        m_axi_input_V_AWCACHE,
        m_axi_input_V_AWPROT,
        m_axi_input_V_AWQOS,
        m_axi_input_V_AWREGION,
        m_axi_input_V_AWUSER,
        m_axi_input_V_WVALID,
        m_axi_input_V_WREADY,
        m_axi_input_V_WDATA,
        m_axi_input_V_WSTRB,
        m_axi_input_V_WLAST,
        m_axi_input_V_WID,
        m_axi_input_V_WUSER,
        m_axi_input_V_ARVALID,
        m_axi_input_V_ARREADY,
        m_axi_input_V_ARADDR,
        m_axi_input_V_ARID,
        m_axi_input_V_ARLEN,
        m_axi_input_V_ARSIZE,
        m_axi_input_V_ARBURST,
        m_axi_input_V_ARLOCK,
        m_axi_input_V_ARCACHE,
        m_axi_input_V_ARPROT,
        m_axi_input_V_ARQOS,
        m_axi_input_V_ARREGION,
        m_axi_input_V_ARUSER,
        m_axi_input_V_RVALID,
        m_axi_input_V_RREADY,
        m_axi_input_V_RDATA,
        m_axi_input_V_RLAST,
        m_axi_input_V_RID,
        m_axi_input_V_RUSER,
        m_axi_input_V_RRESP,
        m_axi_input_V_BVALID,
        m_axi_input_V_BREADY,
        m_axi_input_V_BRESP,
        m_axi_input_V_BID,
        m_axi_input_V_BUSER,
        input_V_offset,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        m_axi_output_V_AWVALID,
        m_axi_output_V_AWREADY,
        m_axi_output_V_AWADDR,
        m_axi_output_V_AWID,
        m_axi_output_V_AWLEN,
        m_axi_output_V_AWSIZE,
        m_axi_output_V_AWBURST,
        m_axi_output_V_AWLOCK,
        m_axi_output_V_AWCACHE,
        m_axi_output_V_AWPROT,
        m_axi_output_V_AWQOS,
        m_axi_output_V_AWREGION,
        m_axi_output_V_AWUSER,
        m_axi_output_V_WVALID,
        m_axi_output_V_WREADY,
        m_axi_output_V_WDATA,
        m_axi_output_V_WSTRB,
        m_axi_output_V_WLAST,
        m_axi_output_V_WID,
        m_axi_output_V_WUSER,
        m_axi_output_V_ARVALID,
        m_axi_output_V_ARREADY,
        m_axi_output_V_ARADDR,
        m_axi_output_V_ARID,
        m_axi_output_V_ARLEN,
        m_axi_output_V_ARSIZE,
        m_axi_output_V_ARBURST,
        m_axi_output_V_ARLOCK,
        m_axi_output_V_ARCACHE,
        m_axi_output_V_ARPROT,
        m_axi_output_V_ARQOS,
        m_axi_output_V_ARREGION,
        m_axi_output_V_ARUSER,
        m_axi_output_V_RVALID,
        m_axi_output_V_RREADY,
        m_axi_output_V_RDATA,
        m_axi_output_V_RLAST,
        m_axi_output_V_RID,
        m_axi_output_V_RUSER,
        m_axi_output_V_RRESP,
        m_axi_output_V_BVALID,
        m_axi_output_V_BREADY,
        m_axi_output_V_BRESP,
        m_axi_output_V_BID,
        m_axi_output_V_BUSER,
        output_V_offset,
        cmpr_chunk_num_0_i,
        ap_clk,
        ap_rst,
        input_V_offset_ap_vld,
        p_read_ap_vld,
        p_read1_ap_vld,
        p_read2_ap_vld,
        p_read3_ap_vld,
        p_read4_ap_vld,
        p_read5_ap_vld,
        p_read6_ap_vld,
        p_read7_ap_vld,
        p_read8_ap_vld,
        p_read9_ap_vld,
        p_read10_ap_vld,
        p_read11_ap_vld,
        p_read12_ap_vld,
        p_read13_ap_vld,
        p_read14_ap_vld,
        p_read15_ap_vld,
        p_read16_ap_vld,
        p_read17_ap_vld,
        p_read18_ap_vld,
        p_read19_ap_vld,
        p_read20_ap_vld,
        p_read21_ap_vld,
        p_read22_ap_vld,
        p_read23_ap_vld,
        p_read24_ap_vld,
        p_read25_ap_vld,
        p_read26_ap_vld,
        p_read27_ap_vld,
        p_read28_ap_vld,
        p_read29_ap_vld,
        p_read30_ap_vld,
        p_read31_ap_vld,
        output_V_offset_ap_vld,
        cmpr_chunk_num_0_i_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_input_V_AWVALID;
input   m_axi_input_V_AWREADY;
output  [63:0] m_axi_input_V_AWADDR;
output  [0:0] m_axi_input_V_AWID;
output  [31:0] m_axi_input_V_AWLEN;
output  [2:0] m_axi_input_V_AWSIZE;
output  [1:0] m_axi_input_V_AWBURST;
output  [1:0] m_axi_input_V_AWLOCK;
output  [3:0] m_axi_input_V_AWCACHE;
output  [2:0] m_axi_input_V_AWPROT;
output  [3:0] m_axi_input_V_AWQOS;
output  [3:0] m_axi_input_V_AWREGION;
output  [0:0] m_axi_input_V_AWUSER;
output   m_axi_input_V_WVALID;
input   m_axi_input_V_WREADY;
output  [511:0] m_axi_input_V_WDATA;
output  [63:0] m_axi_input_V_WSTRB;
output   m_axi_input_V_WLAST;
output  [0:0] m_axi_input_V_WID;
output  [0:0] m_axi_input_V_WUSER;
output   m_axi_input_V_ARVALID;
input   m_axi_input_V_ARREADY;
output  [63:0] m_axi_input_V_ARADDR;
output  [0:0] m_axi_input_V_ARID;
output  [31:0] m_axi_input_V_ARLEN;
output  [2:0] m_axi_input_V_ARSIZE;
output  [1:0] m_axi_input_V_ARBURST;
output  [1:0] m_axi_input_V_ARLOCK;
output  [3:0] m_axi_input_V_ARCACHE;
output  [2:0] m_axi_input_V_ARPROT;
output  [3:0] m_axi_input_V_ARQOS;
output  [3:0] m_axi_input_V_ARREGION;
output  [0:0] m_axi_input_V_ARUSER;
input   m_axi_input_V_RVALID;
output   m_axi_input_V_RREADY;
input  [511:0] m_axi_input_V_RDATA;
input   m_axi_input_V_RLAST;
input  [0:0] m_axi_input_V_RID;
input  [0:0] m_axi_input_V_RUSER;
input  [1:0] m_axi_input_V_RRESP;
input   m_axi_input_V_BVALID;
output   m_axi_input_V_BREADY;
input  [1:0] m_axi_input_V_BRESP;
input  [0:0] m_axi_input_V_BID;
input  [0:0] m_axi_input_V_BUSER;
input  [57:0] input_V_offset;
input  [1023:0] p_read;
input  [1023:0] p_read1;
input  [1023:0] p_read2;
input  [1023:0] p_read3;
input  [1023:0] p_read4;
input  [1023:0] p_read5;
input  [1023:0] p_read6;
input  [1023:0] p_read7;
input  [1023:0] p_read8;
input  [1023:0] p_read9;
input  [1023:0] p_read10;
input  [1023:0] p_read11;
input  [1023:0] p_read12;
input  [1023:0] p_read13;
input  [1023:0] p_read14;
input  [1023:0] p_read15;
input  [10:0] p_read16;
input  [10:0] p_read17;
input  [10:0] p_read18;
input  [10:0] p_read19;
input  [10:0] p_read20;
input  [10:0] p_read21;
input  [10:0] p_read22;
input  [10:0] p_read23;
input  [10:0] p_read24;
input  [10:0] p_read25;
input  [10:0] p_read26;
input  [10:0] p_read27;
input  [10:0] p_read28;
input  [10:0] p_read29;
input  [10:0] p_read30;
input  [9:0] p_read31;
output   m_axi_output_V_AWVALID;
input   m_axi_output_V_AWREADY;
output  [63:0] m_axi_output_V_AWADDR;
output  [0:0] m_axi_output_V_AWID;
output  [31:0] m_axi_output_V_AWLEN;
output  [2:0] m_axi_output_V_AWSIZE;
output  [1:0] m_axi_output_V_AWBURST;
output  [1:0] m_axi_output_V_AWLOCK;
output  [3:0] m_axi_output_V_AWCACHE;
output  [2:0] m_axi_output_V_AWPROT;
output  [3:0] m_axi_output_V_AWQOS;
output  [3:0] m_axi_output_V_AWREGION;
output  [0:0] m_axi_output_V_AWUSER;
output   m_axi_output_V_WVALID;
input   m_axi_output_V_WREADY;
output  [511:0] m_axi_output_V_WDATA;
output  [63:0] m_axi_output_V_WSTRB;
output   m_axi_output_V_WLAST;
output  [0:0] m_axi_output_V_WID;
output  [0:0] m_axi_output_V_WUSER;
output   m_axi_output_V_ARVALID;
input   m_axi_output_V_ARREADY;
output  [63:0] m_axi_output_V_ARADDR;
output  [0:0] m_axi_output_V_ARID;
output  [31:0] m_axi_output_V_ARLEN;
output  [2:0] m_axi_output_V_ARSIZE;
output  [1:0] m_axi_output_V_ARBURST;
output  [1:0] m_axi_output_V_ARLOCK;
output  [3:0] m_axi_output_V_ARCACHE;
output  [2:0] m_axi_output_V_ARPROT;
output  [3:0] m_axi_output_V_ARQOS;
output  [3:0] m_axi_output_V_ARREGION;
output  [0:0] m_axi_output_V_ARUSER;
input   m_axi_output_V_RVALID;
output   m_axi_output_V_RREADY;
input  [511:0] m_axi_output_V_RDATA;
input   m_axi_output_V_RLAST;
input  [0:0] m_axi_output_V_RID;
input  [0:0] m_axi_output_V_RUSER;
input  [1:0] m_axi_output_V_RRESP;
input   m_axi_output_V_BVALID;
output   m_axi_output_V_BREADY;
input  [1:0] m_axi_output_V_BRESP;
input  [0:0] m_axi_output_V_BID;
input  [0:0] m_axi_output_V_BUSER;
input  [57:0] output_V_offset;
input  [2:0] cmpr_chunk_num_0_i;
input   ap_clk;
input   ap_rst;
input   input_V_offset_ap_vld;
input   p_read_ap_vld;
input   p_read1_ap_vld;
input   p_read2_ap_vld;
input   p_read3_ap_vld;
input   p_read4_ap_vld;
input   p_read5_ap_vld;
input   p_read6_ap_vld;
input   p_read7_ap_vld;
input   p_read8_ap_vld;
input   p_read9_ap_vld;
input   p_read10_ap_vld;
input   p_read11_ap_vld;
input   p_read12_ap_vld;
input   p_read13_ap_vld;
input   p_read14_ap_vld;
input   p_read15_ap_vld;
input   p_read16_ap_vld;
input   p_read17_ap_vld;
input   p_read18_ap_vld;
input   p_read19_ap_vld;
input   p_read20_ap_vld;
input   p_read21_ap_vld;
input   p_read22_ap_vld;
input   p_read23_ap_vld;
input   p_read24_ap_vld;
input   p_read25_ap_vld;
input   p_read26_ap_vld;
input   p_read27_ap_vld;
input   p_read28_ap_vld;
input   p_read29_ap_vld;
input   p_read30_ap_vld;
input   p_read31_ap_vld;
input   output_V_offset_ap_vld;
input   cmpr_chunk_num_0_i_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg ap_done;
reg ap_ready;
reg ap_idle;

wire    dataflow_in_loop_subloop_U0_m_axi_input_V_AWVALID;
wire   [63:0] dataflow_in_loop_subloop_U0_m_axi_input_V_AWADDR;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_input_V_AWID;
wire   [31:0] dataflow_in_loop_subloop_U0_m_axi_input_V_AWLEN;
wire   [2:0] dataflow_in_loop_subloop_U0_m_axi_input_V_AWSIZE;
wire   [1:0] dataflow_in_loop_subloop_U0_m_axi_input_V_AWBURST;
wire   [1:0] dataflow_in_loop_subloop_U0_m_axi_input_V_AWLOCK;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_input_V_AWCACHE;
wire   [2:0] dataflow_in_loop_subloop_U0_m_axi_input_V_AWPROT;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_input_V_AWQOS;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_input_V_AWREGION;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_input_V_AWUSER;
wire    dataflow_in_loop_subloop_U0_m_axi_input_V_WVALID;
wire   [511:0] dataflow_in_loop_subloop_U0_m_axi_input_V_WDATA;
wire   [63:0] dataflow_in_loop_subloop_U0_m_axi_input_V_WSTRB;
wire    dataflow_in_loop_subloop_U0_m_axi_input_V_WLAST;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_input_V_WID;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_input_V_WUSER;
wire    dataflow_in_loop_subloop_U0_m_axi_input_V_ARVALID;
wire   [63:0] dataflow_in_loop_subloop_U0_m_axi_input_V_ARADDR;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_input_V_ARID;
wire   [31:0] dataflow_in_loop_subloop_U0_m_axi_input_V_ARLEN;
wire   [2:0] dataflow_in_loop_subloop_U0_m_axi_input_V_ARSIZE;
wire   [1:0] dataflow_in_loop_subloop_U0_m_axi_input_V_ARBURST;
wire   [1:0] dataflow_in_loop_subloop_U0_m_axi_input_V_ARLOCK;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_input_V_ARCACHE;
wire   [2:0] dataflow_in_loop_subloop_U0_m_axi_input_V_ARPROT;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_input_V_ARQOS;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_input_V_ARREGION;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_input_V_ARUSER;
wire    dataflow_in_loop_subloop_U0_m_axi_input_V_RREADY;
wire    dataflow_in_loop_subloop_U0_m_axi_input_V_BREADY;
wire    dataflow_in_loop_subloop_U0_m_axi_output_V_AWVALID;
wire   [63:0] dataflow_in_loop_subloop_U0_m_axi_output_V_AWADDR;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_output_V_AWID;
wire   [31:0] dataflow_in_loop_subloop_U0_m_axi_output_V_AWLEN;
wire   [2:0] dataflow_in_loop_subloop_U0_m_axi_output_V_AWSIZE;
wire   [1:0] dataflow_in_loop_subloop_U0_m_axi_output_V_AWBURST;
wire   [1:0] dataflow_in_loop_subloop_U0_m_axi_output_V_AWLOCK;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_output_V_AWCACHE;
wire   [2:0] dataflow_in_loop_subloop_U0_m_axi_output_V_AWPROT;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_output_V_AWQOS;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_output_V_AWREGION;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_output_V_AWUSER;
wire    dataflow_in_loop_subloop_U0_m_axi_output_V_WVALID;
wire   [511:0] dataflow_in_loop_subloop_U0_m_axi_output_V_WDATA;
wire   [63:0] dataflow_in_loop_subloop_U0_m_axi_output_V_WSTRB;
wire    dataflow_in_loop_subloop_U0_m_axi_output_V_WLAST;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_output_V_WID;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_output_V_WUSER;
wire    dataflow_in_loop_subloop_U0_m_axi_output_V_ARVALID;
wire   [63:0] dataflow_in_loop_subloop_U0_m_axi_output_V_ARADDR;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_output_V_ARID;
wire   [31:0] dataflow_in_loop_subloop_U0_m_axi_output_V_ARLEN;
wire   [2:0] dataflow_in_loop_subloop_U0_m_axi_output_V_ARSIZE;
wire   [1:0] dataflow_in_loop_subloop_U0_m_axi_output_V_ARBURST;
wire   [1:0] dataflow_in_loop_subloop_U0_m_axi_output_V_ARLOCK;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_output_V_ARCACHE;
wire   [2:0] dataflow_in_loop_subloop_U0_m_axi_output_V_ARPROT;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_output_V_ARQOS;
wire   [3:0] dataflow_in_loop_subloop_U0_m_axi_output_V_ARREGION;
wire   [0:0] dataflow_in_loop_subloop_U0_m_axi_output_V_ARUSER;
wire    dataflow_in_loop_subloop_U0_m_axi_output_V_RREADY;
wire    dataflow_in_loop_subloop_U0_m_axi_output_V_BREADY;
wire   [1:0] dataflow_in_loop_subloop_U0_cmpr_chunk_num_0_i;
wire    dataflow_in_loop_subloop_U0_ap_start;
wire    dataflow_in_loop_subloop_U0_ap_done;
wire    dataflow_in_loop_subloop_U0_ap_ready;
wire    dataflow_in_loop_subloop_U0_ap_idle;
reg    dataflow_in_loop_subloop_U0_ap_continue;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
reg   [6:0] loop_dataflow_input_count;
reg   [6:0] loop_dataflow_output_count;
wire   [6:0] bound_minus_1;
wire    dataflow_in_loop_subloop_U0_start_full_n;
wire    dataflow_in_loop_subloop_U0_start_write;

// power-on initialization
initial begin
#0 loop_dataflow_input_count = 7'd0;
#0 loop_dataflow_output_count = 7'd0;
end

tancalc_dataflow_in_loop_subloop dataflow_in_loop_subloop_U0(
    .m_axi_input_V_AWVALID(dataflow_in_loop_subloop_U0_m_axi_input_V_AWVALID),
    .m_axi_input_V_AWREADY(1'b0),
    .m_axi_input_V_AWADDR(dataflow_in_loop_subloop_U0_m_axi_input_V_AWADDR),
    .m_axi_input_V_AWID(dataflow_in_loop_subloop_U0_m_axi_input_V_AWID),
    .m_axi_input_V_AWLEN(dataflow_in_loop_subloop_U0_m_axi_input_V_AWLEN),
    .m_axi_input_V_AWSIZE(dataflow_in_loop_subloop_U0_m_axi_input_V_AWSIZE),
    .m_axi_input_V_AWBURST(dataflow_in_loop_subloop_U0_m_axi_input_V_AWBURST),
    .m_axi_input_V_AWLOCK(dataflow_in_loop_subloop_U0_m_axi_input_V_AWLOCK),
    .m_axi_input_V_AWCACHE(dataflow_in_loop_subloop_U0_m_axi_input_V_AWCACHE),
    .m_axi_input_V_AWPROT(dataflow_in_loop_subloop_U0_m_axi_input_V_AWPROT),
    .m_axi_input_V_AWQOS(dataflow_in_loop_subloop_U0_m_axi_input_V_AWQOS),
    .m_axi_input_V_AWREGION(dataflow_in_loop_subloop_U0_m_axi_input_V_AWREGION),
    .m_axi_input_V_AWUSER(dataflow_in_loop_subloop_U0_m_axi_input_V_AWUSER),
    .m_axi_input_V_WVALID(dataflow_in_loop_subloop_U0_m_axi_input_V_WVALID),
    .m_axi_input_V_WREADY(1'b0),
    .m_axi_input_V_WDATA(dataflow_in_loop_subloop_U0_m_axi_input_V_WDATA),
    .m_axi_input_V_WSTRB(dataflow_in_loop_subloop_U0_m_axi_input_V_WSTRB),
    .m_axi_input_V_WLAST(dataflow_in_loop_subloop_U0_m_axi_input_V_WLAST),
    .m_axi_input_V_WID(dataflow_in_loop_subloop_U0_m_axi_input_V_WID),
    .m_axi_input_V_WUSER(dataflow_in_loop_subloop_U0_m_axi_input_V_WUSER),
    .m_axi_input_V_ARVALID(dataflow_in_loop_subloop_U0_m_axi_input_V_ARVALID),
    .m_axi_input_V_ARREADY(m_axi_input_V_ARREADY),
    .m_axi_input_V_ARADDR(dataflow_in_loop_subloop_U0_m_axi_input_V_ARADDR),
    .m_axi_input_V_ARID(dataflow_in_loop_subloop_U0_m_axi_input_V_ARID),
    .m_axi_input_V_ARLEN(dataflow_in_loop_subloop_U0_m_axi_input_V_ARLEN),
    .m_axi_input_V_ARSIZE(dataflow_in_loop_subloop_U0_m_axi_input_V_ARSIZE),
    .m_axi_input_V_ARBURST(dataflow_in_loop_subloop_U0_m_axi_input_V_ARBURST),
    .m_axi_input_V_ARLOCK(dataflow_in_loop_subloop_U0_m_axi_input_V_ARLOCK),
    .m_axi_input_V_ARCACHE(dataflow_in_loop_subloop_U0_m_axi_input_V_ARCACHE),
    .m_axi_input_V_ARPROT(dataflow_in_loop_subloop_U0_m_axi_input_V_ARPROT),
    .m_axi_input_V_ARQOS(dataflow_in_loop_subloop_U0_m_axi_input_V_ARQOS),
    .m_axi_input_V_ARREGION(dataflow_in_loop_subloop_U0_m_axi_input_V_ARREGION),
    .m_axi_input_V_ARUSER(dataflow_in_loop_subloop_U0_m_axi_input_V_ARUSER),
    .m_axi_input_V_RVALID(m_axi_input_V_RVALID),
    .m_axi_input_V_RREADY(dataflow_in_loop_subloop_U0_m_axi_input_V_RREADY),
    .m_axi_input_V_RDATA(m_axi_input_V_RDATA),
    .m_axi_input_V_RLAST(m_axi_input_V_RLAST),
    .m_axi_input_V_RID(m_axi_input_V_RID),
    .m_axi_input_V_RUSER(m_axi_input_V_RUSER),
    .m_axi_input_V_RRESP(m_axi_input_V_RRESP),
    .m_axi_input_V_BVALID(1'b0),
    .m_axi_input_V_BREADY(dataflow_in_loop_subloop_U0_m_axi_input_V_BREADY),
    .m_axi_input_V_BRESP(2'd0),
    .m_axi_input_V_BID(1'd0),
    .m_axi_input_V_BUSER(1'd0),
    .input_V_offset(input_V_offset),
    .data_num_0_i(loop_dataflow_input_count),
    .p_read(p_read),
    .p_read1(p_read1),
    .p_read2(p_read2),
    .p_read3(p_read3),
    .p_read4(p_read4),
    .p_read5(p_read5),
    .p_read6(p_read6),
    .p_read7(p_read7),
    .p_read8(p_read8),
    .p_read9(p_read9),
    .p_read10(p_read10),
    .p_read11(p_read11),
    .p_read12(p_read12),
    .p_read13(p_read13),
    .p_read14(p_read14),
    .p_read15(p_read15),
    .p_read16(p_read16),
    .p_read17(p_read17),
    .p_read18(p_read18),
    .p_read19(p_read19),
    .p_read20(p_read20),
    .p_read21(p_read21),
    .p_read22(p_read22),
    .p_read23(p_read23),
    .p_read24(p_read24),
    .p_read25(p_read25),
    .p_read26(p_read26),
    .p_read27(p_read27),
    .p_read28(p_read28),
    .p_read29(p_read29),
    .p_read30(p_read30),
    .p_read31(p_read31),
    .m_axi_output_V_AWVALID(dataflow_in_loop_subloop_U0_m_axi_output_V_AWVALID),
    .m_axi_output_V_AWREADY(m_axi_output_V_AWREADY),
    .m_axi_output_V_AWADDR(dataflow_in_loop_subloop_U0_m_axi_output_V_AWADDR),
    .m_axi_output_V_AWID(dataflow_in_loop_subloop_U0_m_axi_output_V_AWID),
    .m_axi_output_V_AWLEN(dataflow_in_loop_subloop_U0_m_axi_output_V_AWLEN),
    .m_axi_output_V_AWSIZE(dataflow_in_loop_subloop_U0_m_axi_output_V_AWSIZE),
    .m_axi_output_V_AWBURST(dataflow_in_loop_subloop_U0_m_axi_output_V_AWBURST),
    .m_axi_output_V_AWLOCK(dataflow_in_loop_subloop_U0_m_axi_output_V_AWLOCK),
    .m_axi_output_V_AWCACHE(dataflow_in_loop_subloop_U0_m_axi_output_V_AWCACHE),
    .m_axi_output_V_AWPROT(dataflow_in_loop_subloop_U0_m_axi_output_V_AWPROT),
    .m_axi_output_V_AWQOS(dataflow_in_loop_subloop_U0_m_axi_output_V_AWQOS),
    .m_axi_output_V_AWREGION(dataflow_in_loop_subloop_U0_m_axi_output_V_AWREGION),
    .m_axi_output_V_AWUSER(dataflow_in_loop_subloop_U0_m_axi_output_V_AWUSER),
    .m_axi_output_V_WVALID(dataflow_in_loop_subloop_U0_m_axi_output_V_WVALID),
    .m_axi_output_V_WREADY(m_axi_output_V_WREADY),
    .m_axi_output_V_WDATA(dataflow_in_loop_subloop_U0_m_axi_output_V_WDATA),
    .m_axi_output_V_WSTRB(dataflow_in_loop_subloop_U0_m_axi_output_V_WSTRB),
    .m_axi_output_V_WLAST(dataflow_in_loop_subloop_U0_m_axi_output_V_WLAST),
    .m_axi_output_V_WID(dataflow_in_loop_subloop_U0_m_axi_output_V_WID),
    .m_axi_output_V_WUSER(dataflow_in_loop_subloop_U0_m_axi_output_V_WUSER),
    .m_axi_output_V_ARVALID(dataflow_in_loop_subloop_U0_m_axi_output_V_ARVALID),
    .m_axi_output_V_ARREADY(1'b0),
    .m_axi_output_V_ARADDR(dataflow_in_loop_subloop_U0_m_axi_output_V_ARADDR),
    .m_axi_output_V_ARID(dataflow_in_loop_subloop_U0_m_axi_output_V_ARID),
    .m_axi_output_V_ARLEN(dataflow_in_loop_subloop_U0_m_axi_output_V_ARLEN),
    .m_axi_output_V_ARSIZE(dataflow_in_loop_subloop_U0_m_axi_output_V_ARSIZE),
    .m_axi_output_V_ARBURST(dataflow_in_loop_subloop_U0_m_axi_output_V_ARBURST),
    .m_axi_output_V_ARLOCK(dataflow_in_loop_subloop_U0_m_axi_output_V_ARLOCK),
    .m_axi_output_V_ARCACHE(dataflow_in_loop_subloop_U0_m_axi_output_V_ARCACHE),
    .m_axi_output_V_ARPROT(dataflow_in_loop_subloop_U0_m_axi_output_V_ARPROT),
    .m_axi_output_V_ARQOS(dataflow_in_loop_subloop_U0_m_axi_output_V_ARQOS),
    .m_axi_output_V_ARREGION(dataflow_in_loop_subloop_U0_m_axi_output_V_ARREGION),
    .m_axi_output_V_ARUSER(dataflow_in_loop_subloop_U0_m_axi_output_V_ARUSER),
    .m_axi_output_V_RVALID(1'b0),
    .m_axi_output_V_RREADY(dataflow_in_loop_subloop_U0_m_axi_output_V_RREADY),
    .m_axi_output_V_RDATA(512'd0),
    .m_axi_output_V_RLAST(1'b0),
    .m_axi_output_V_RID(1'd0),
    .m_axi_output_V_RUSER(1'd0),
    .m_axi_output_V_RRESP(2'd0),
    .m_axi_output_V_BVALID(m_axi_output_V_BVALID),
    .m_axi_output_V_BREADY(dataflow_in_loop_subloop_U0_m_axi_output_V_BREADY),
    .m_axi_output_V_BRESP(m_axi_output_V_BRESP),
    .m_axi_output_V_BID(m_axi_output_V_BID),
    .m_axi_output_V_BUSER(m_axi_output_V_BUSER),
    .output_V_offset(output_V_offset),
    .cmpr_chunk_num_0_i(dataflow_in_loop_subloop_U0_cmpr_chunk_num_0_i),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .input_V_offset_ap_vld(input_V_offset_ap_vld),
    .data_num_0_i_ap_vld(1'b0),
    .p_read_ap_vld(p_read_ap_vld),
    .p_read1_ap_vld(p_read1_ap_vld),
    .p_read2_ap_vld(p_read2_ap_vld),
    .p_read3_ap_vld(p_read3_ap_vld),
    .p_read4_ap_vld(p_read4_ap_vld),
    .p_read5_ap_vld(p_read5_ap_vld),
    .p_read6_ap_vld(p_read6_ap_vld),
    .p_read7_ap_vld(p_read7_ap_vld),
    .p_read8_ap_vld(p_read8_ap_vld),
    .p_read9_ap_vld(p_read9_ap_vld),
    .p_read10_ap_vld(p_read10_ap_vld),
    .p_read11_ap_vld(p_read11_ap_vld),
    .p_read12_ap_vld(p_read12_ap_vld),
    .p_read13_ap_vld(p_read13_ap_vld),
    .p_read14_ap_vld(p_read14_ap_vld),
    .p_read15_ap_vld(p_read15_ap_vld),
    .p_read16_ap_vld(p_read16_ap_vld),
    .p_read17_ap_vld(p_read17_ap_vld),
    .p_read18_ap_vld(p_read18_ap_vld),
    .p_read19_ap_vld(p_read19_ap_vld),
    .p_read20_ap_vld(p_read20_ap_vld),
    .p_read21_ap_vld(p_read21_ap_vld),
    .p_read22_ap_vld(p_read22_ap_vld),
    .p_read23_ap_vld(p_read23_ap_vld),
    .p_read24_ap_vld(p_read24_ap_vld),
    .p_read25_ap_vld(p_read25_ap_vld),
    .p_read26_ap_vld(p_read26_ap_vld),
    .p_read27_ap_vld(p_read27_ap_vld),
    .p_read28_ap_vld(p_read28_ap_vld),
    .p_read29_ap_vld(p_read29_ap_vld),
    .p_read30_ap_vld(p_read30_ap_vld),
    .p_read31_ap_vld(p_read31_ap_vld),
    .cmpr_chunk_num_0_i_ap_vld(cmpr_chunk_num_0_i_ap_vld),
    .output_V_offset_ap_vld(output_V_offset_ap_vld),
    .ap_start(dataflow_in_loop_subloop_U0_ap_start),
    .ap_done(dataflow_in_loop_subloop_U0_ap_done),
    .ap_ready(dataflow_in_loop_subloop_U0_ap_ready),
    .ap_idle(dataflow_in_loop_subloop_U0_ap_idle),
    .ap_continue(dataflow_in_loop_subloop_U0_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_input_count <= 7'd0;
    end else begin
        if ((~(loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_subloop_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= (loop_dataflow_input_count + 7'd1);
        end else if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_subloop_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_output_count <= 7'd0;
    end else begin
        if ((~(loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_subloop_U0_ap_continue == 1'b1) & (dataflow_in_loop_subloop_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= (loop_dataflow_output_count + 7'd1);
        end else if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_subloop_U0_ap_continue == 1'b1) & (dataflow_in_loop_subloop_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= 7'd0;
        end
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_subloop_U0_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == 7'd0) & (ap_start == 1'b0) & (dataflow_in_loop_subloop_U0_ap_idle == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_subloop_U0_ap_ready == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~(loop_dataflow_output_count == bound_minus_1) | (ap_continue == 1'b1))) begin
        dataflow_in_loop_subloop_U0_ap_continue = 1'b1;
    end else begin
        dataflow_in_loop_subloop_U0_ap_continue = 1'b0;
    end
end

assign ap_sync_continue = ap_continue;

assign ap_sync_done = dataflow_in_loop_subloop_U0_ap_done;

assign ap_sync_ready = dataflow_in_loop_subloop_U0_ap_ready;

assign bound_minus_1 = (7'd64 - 7'd1);

assign dataflow_in_loop_subloop_U0_ap_start = ap_start;

assign dataflow_in_loop_subloop_U0_cmpr_chunk_num_0_i = {{cmpr_chunk_num_0_i[(2 - 3'd1):0]}};

assign dataflow_in_loop_subloop_U0_start_full_n = 1'b1;

assign dataflow_in_loop_subloop_U0_start_write = 1'b0;

assign m_axi_input_V_ARADDR = dataflow_in_loop_subloop_U0_m_axi_input_V_ARADDR;

assign m_axi_input_V_ARBURST = dataflow_in_loop_subloop_U0_m_axi_input_V_ARBURST;

assign m_axi_input_V_ARCACHE = dataflow_in_loop_subloop_U0_m_axi_input_V_ARCACHE;

assign m_axi_input_V_ARID = dataflow_in_loop_subloop_U0_m_axi_input_V_ARID;

assign m_axi_input_V_ARLEN = dataflow_in_loop_subloop_U0_m_axi_input_V_ARLEN;

assign m_axi_input_V_ARLOCK = dataflow_in_loop_subloop_U0_m_axi_input_V_ARLOCK;

assign m_axi_input_V_ARPROT = dataflow_in_loop_subloop_U0_m_axi_input_V_ARPROT;

assign m_axi_input_V_ARQOS = dataflow_in_loop_subloop_U0_m_axi_input_V_ARQOS;

assign m_axi_input_V_ARREGION = dataflow_in_loop_subloop_U0_m_axi_input_V_ARREGION;

assign m_axi_input_V_ARSIZE = dataflow_in_loop_subloop_U0_m_axi_input_V_ARSIZE;

assign m_axi_input_V_ARUSER = dataflow_in_loop_subloop_U0_m_axi_input_V_ARUSER;

assign m_axi_input_V_ARVALID = dataflow_in_loop_subloop_U0_m_axi_input_V_ARVALID;

assign m_axi_input_V_AWADDR = 64'd0;

assign m_axi_input_V_AWBURST = 2'd0;

assign m_axi_input_V_AWCACHE = 4'd0;

assign m_axi_input_V_AWID = 1'd0;

assign m_axi_input_V_AWLEN = 32'd0;

assign m_axi_input_V_AWLOCK = 2'd0;

assign m_axi_input_V_AWPROT = 3'd0;

assign m_axi_input_V_AWQOS = 4'd0;

assign m_axi_input_V_AWREGION = 4'd0;

assign m_axi_input_V_AWSIZE = 3'd0;

assign m_axi_input_V_AWUSER = 1'd0;

assign m_axi_input_V_AWVALID = 1'b0;

assign m_axi_input_V_BREADY = 1'b0;

assign m_axi_input_V_RREADY = dataflow_in_loop_subloop_U0_m_axi_input_V_RREADY;

assign m_axi_input_V_WDATA = 512'd0;

assign m_axi_input_V_WID = 1'd0;

assign m_axi_input_V_WLAST = 1'b0;

assign m_axi_input_V_WSTRB = 64'd0;

assign m_axi_input_V_WUSER = 1'd0;

assign m_axi_input_V_WVALID = 1'b0;

assign m_axi_output_V_ARADDR = 64'd0;

assign m_axi_output_V_ARBURST = 2'd0;

assign m_axi_output_V_ARCACHE = 4'd0;

assign m_axi_output_V_ARID = 1'd0;

assign m_axi_output_V_ARLEN = 32'd0;

assign m_axi_output_V_ARLOCK = 2'd0;

assign m_axi_output_V_ARPROT = 3'd0;

assign m_axi_output_V_ARQOS = 4'd0;

assign m_axi_output_V_ARREGION = 4'd0;

assign m_axi_output_V_ARSIZE = 3'd0;

assign m_axi_output_V_ARUSER = 1'd0;

assign m_axi_output_V_ARVALID = 1'b0;

assign m_axi_output_V_AWADDR = dataflow_in_loop_subloop_U0_m_axi_output_V_AWADDR;

assign m_axi_output_V_AWBURST = dataflow_in_loop_subloop_U0_m_axi_output_V_AWBURST;

assign m_axi_output_V_AWCACHE = dataflow_in_loop_subloop_U0_m_axi_output_V_AWCACHE;

assign m_axi_output_V_AWID = dataflow_in_loop_subloop_U0_m_axi_output_V_AWID;

assign m_axi_output_V_AWLEN = dataflow_in_loop_subloop_U0_m_axi_output_V_AWLEN;

assign m_axi_output_V_AWLOCK = dataflow_in_loop_subloop_U0_m_axi_output_V_AWLOCK;

assign m_axi_output_V_AWPROT = dataflow_in_loop_subloop_U0_m_axi_output_V_AWPROT;

assign m_axi_output_V_AWQOS = dataflow_in_loop_subloop_U0_m_axi_output_V_AWQOS;

assign m_axi_output_V_AWREGION = dataflow_in_loop_subloop_U0_m_axi_output_V_AWREGION;

assign m_axi_output_V_AWSIZE = dataflow_in_loop_subloop_U0_m_axi_output_V_AWSIZE;

assign m_axi_output_V_AWUSER = dataflow_in_loop_subloop_U0_m_axi_output_V_AWUSER;

assign m_axi_output_V_AWVALID = dataflow_in_loop_subloop_U0_m_axi_output_V_AWVALID;

assign m_axi_output_V_BREADY = dataflow_in_loop_subloop_U0_m_axi_output_V_BREADY;

assign m_axi_output_V_RREADY = 1'b0;

assign m_axi_output_V_WDATA = dataflow_in_loop_subloop_U0_m_axi_output_V_WDATA;

assign m_axi_output_V_WID = dataflow_in_loop_subloop_U0_m_axi_output_V_WID;

assign m_axi_output_V_WLAST = dataflow_in_loop_subloop_U0_m_axi_output_V_WLAST;

assign m_axi_output_V_WSTRB = dataflow_in_loop_subloop_U0_m_axi_output_V_WSTRB;

assign m_axi_output_V_WUSER = dataflow_in_loop_subloop_U0_m_axi_output_V_WUSER;

assign m_axi_output_V_WVALID = dataflow_in_loop_subloop_U0_m_axi_output_V_WVALID;

endmodule //tancalc_dataflow_parent_loop_proc
