-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tancalc_dataflow_parent_loop_proc is
port (
    m_axi_input_V_AWVALID : OUT STD_LOGIC;
    m_axi_input_V_AWREADY : IN STD_LOGIC;
    m_axi_input_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_input_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_input_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_input_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_input_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_V_WVALID : OUT STD_LOGIC;
    m_axi_input_V_WREADY : IN STD_LOGIC;
    m_axi_input_V_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_input_V_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_input_V_WLAST : OUT STD_LOGIC;
    m_axi_input_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_V_ARVALID : OUT STD_LOGIC;
    m_axi_input_V_ARREADY : IN STD_LOGIC;
    m_axi_input_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_input_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_input_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_input_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_input_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_V_RVALID : IN STD_LOGIC;
    m_axi_input_V_RREADY : OUT STD_LOGIC;
    m_axi_input_V_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_input_V_RLAST : IN STD_LOGIC;
    m_axi_input_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_V_BVALID : IN STD_LOGIC;
    m_axi_input_V_BREADY : OUT STD_LOGIC;
    m_axi_input_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_V_offset : IN STD_LOGIC_VECTOR (57 downto 0);
    p_read : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read19 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read20 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read21 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read22 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read23 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read24 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read25 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read26 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read27 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read28 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read29 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read30 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read31 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read32 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read33 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read34 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read35 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read36 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read37 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read38 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read39 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read40 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read41 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read42 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read43 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read44 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read45 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read46 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read47 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read48 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read49 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read50 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read51 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read52 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read53 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read54 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read55 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read56 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read57 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read58 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read59 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read60 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read61 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read62 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read63 : IN STD_LOGIC_VECTOR (1023 downto 0);
    p_read64 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read65 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read66 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read67 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read68 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read69 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read70 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read71 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read72 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read73 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read74 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read75 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read76 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read77 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read78 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read79 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read80 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read81 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read82 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read83 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read84 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read85 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read86 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read87 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read88 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read89 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read90 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read91 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read92 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read93 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read94 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read95 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read96 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read97 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read98 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read99 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read100 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read101 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read102 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read103 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read104 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read105 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read106 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read107 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read108 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read109 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read110 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read111 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read112 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read113 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read114 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read115 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read116 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read117 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read118 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read119 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read120 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read121 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read122 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read123 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read124 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read125 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read126 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read127 : IN STD_LOGIC_VECTOR (10 downto 0);
    result_i : IN STD_LOGIC_VECTOR (31 downto 0);
    result_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    input_V_offset_ap_vld : IN STD_LOGIC;
    p_read_ap_vld : IN STD_LOGIC;
    p_read1_ap_vld : IN STD_LOGIC;
    p_read2_ap_vld : IN STD_LOGIC;
    p_read3_ap_vld : IN STD_LOGIC;
    p_read4_ap_vld : IN STD_LOGIC;
    p_read5_ap_vld : IN STD_LOGIC;
    p_read6_ap_vld : IN STD_LOGIC;
    p_read7_ap_vld : IN STD_LOGIC;
    p_read8_ap_vld : IN STD_LOGIC;
    p_read9_ap_vld : IN STD_LOGIC;
    p_read10_ap_vld : IN STD_LOGIC;
    p_read11_ap_vld : IN STD_LOGIC;
    p_read12_ap_vld : IN STD_LOGIC;
    p_read13_ap_vld : IN STD_LOGIC;
    p_read14_ap_vld : IN STD_LOGIC;
    p_read15_ap_vld : IN STD_LOGIC;
    p_read16_ap_vld : IN STD_LOGIC;
    p_read17_ap_vld : IN STD_LOGIC;
    p_read18_ap_vld : IN STD_LOGIC;
    p_read19_ap_vld : IN STD_LOGIC;
    p_read20_ap_vld : IN STD_LOGIC;
    p_read21_ap_vld : IN STD_LOGIC;
    p_read22_ap_vld : IN STD_LOGIC;
    p_read23_ap_vld : IN STD_LOGIC;
    p_read24_ap_vld : IN STD_LOGIC;
    p_read25_ap_vld : IN STD_LOGIC;
    p_read26_ap_vld : IN STD_LOGIC;
    p_read27_ap_vld : IN STD_LOGIC;
    p_read28_ap_vld : IN STD_LOGIC;
    p_read29_ap_vld : IN STD_LOGIC;
    p_read30_ap_vld : IN STD_LOGIC;
    p_read31_ap_vld : IN STD_LOGIC;
    p_read32_ap_vld : IN STD_LOGIC;
    p_read33_ap_vld : IN STD_LOGIC;
    p_read34_ap_vld : IN STD_LOGIC;
    p_read35_ap_vld : IN STD_LOGIC;
    p_read36_ap_vld : IN STD_LOGIC;
    p_read37_ap_vld : IN STD_LOGIC;
    p_read38_ap_vld : IN STD_LOGIC;
    p_read39_ap_vld : IN STD_LOGIC;
    p_read40_ap_vld : IN STD_LOGIC;
    p_read41_ap_vld : IN STD_LOGIC;
    p_read42_ap_vld : IN STD_LOGIC;
    p_read43_ap_vld : IN STD_LOGIC;
    p_read44_ap_vld : IN STD_LOGIC;
    p_read45_ap_vld : IN STD_LOGIC;
    p_read46_ap_vld : IN STD_LOGIC;
    p_read47_ap_vld : IN STD_LOGIC;
    p_read48_ap_vld : IN STD_LOGIC;
    p_read49_ap_vld : IN STD_LOGIC;
    p_read50_ap_vld : IN STD_LOGIC;
    p_read51_ap_vld : IN STD_LOGIC;
    p_read52_ap_vld : IN STD_LOGIC;
    p_read53_ap_vld : IN STD_LOGIC;
    p_read54_ap_vld : IN STD_LOGIC;
    p_read55_ap_vld : IN STD_LOGIC;
    p_read56_ap_vld : IN STD_LOGIC;
    p_read57_ap_vld : IN STD_LOGIC;
    p_read58_ap_vld : IN STD_LOGIC;
    p_read59_ap_vld : IN STD_LOGIC;
    p_read60_ap_vld : IN STD_LOGIC;
    p_read61_ap_vld : IN STD_LOGIC;
    p_read62_ap_vld : IN STD_LOGIC;
    p_read63_ap_vld : IN STD_LOGIC;
    p_read64_ap_vld : IN STD_LOGIC;
    p_read65_ap_vld : IN STD_LOGIC;
    p_read66_ap_vld : IN STD_LOGIC;
    p_read67_ap_vld : IN STD_LOGIC;
    p_read68_ap_vld : IN STD_LOGIC;
    p_read69_ap_vld : IN STD_LOGIC;
    p_read70_ap_vld : IN STD_LOGIC;
    p_read71_ap_vld : IN STD_LOGIC;
    p_read72_ap_vld : IN STD_LOGIC;
    p_read73_ap_vld : IN STD_LOGIC;
    p_read74_ap_vld : IN STD_LOGIC;
    p_read75_ap_vld : IN STD_LOGIC;
    p_read76_ap_vld : IN STD_LOGIC;
    p_read77_ap_vld : IN STD_LOGIC;
    p_read78_ap_vld : IN STD_LOGIC;
    p_read79_ap_vld : IN STD_LOGIC;
    p_read80_ap_vld : IN STD_LOGIC;
    p_read81_ap_vld : IN STD_LOGIC;
    p_read82_ap_vld : IN STD_LOGIC;
    p_read83_ap_vld : IN STD_LOGIC;
    p_read84_ap_vld : IN STD_LOGIC;
    p_read85_ap_vld : IN STD_LOGIC;
    p_read86_ap_vld : IN STD_LOGIC;
    p_read87_ap_vld : IN STD_LOGIC;
    p_read88_ap_vld : IN STD_LOGIC;
    p_read89_ap_vld : IN STD_LOGIC;
    p_read90_ap_vld : IN STD_LOGIC;
    p_read91_ap_vld : IN STD_LOGIC;
    p_read92_ap_vld : IN STD_LOGIC;
    p_read93_ap_vld : IN STD_LOGIC;
    p_read94_ap_vld : IN STD_LOGIC;
    p_read95_ap_vld : IN STD_LOGIC;
    p_read96_ap_vld : IN STD_LOGIC;
    p_read97_ap_vld : IN STD_LOGIC;
    p_read98_ap_vld : IN STD_LOGIC;
    p_read99_ap_vld : IN STD_LOGIC;
    p_read100_ap_vld : IN STD_LOGIC;
    p_read101_ap_vld : IN STD_LOGIC;
    p_read102_ap_vld : IN STD_LOGIC;
    p_read103_ap_vld : IN STD_LOGIC;
    p_read104_ap_vld : IN STD_LOGIC;
    p_read105_ap_vld : IN STD_LOGIC;
    p_read106_ap_vld : IN STD_LOGIC;
    p_read107_ap_vld : IN STD_LOGIC;
    p_read108_ap_vld : IN STD_LOGIC;
    p_read109_ap_vld : IN STD_LOGIC;
    p_read110_ap_vld : IN STD_LOGIC;
    p_read111_ap_vld : IN STD_LOGIC;
    p_read112_ap_vld : IN STD_LOGIC;
    p_read113_ap_vld : IN STD_LOGIC;
    p_read114_ap_vld : IN STD_LOGIC;
    p_read115_ap_vld : IN STD_LOGIC;
    p_read116_ap_vld : IN STD_LOGIC;
    p_read117_ap_vld : IN STD_LOGIC;
    p_read118_ap_vld : IN STD_LOGIC;
    p_read119_ap_vld : IN STD_LOGIC;
    p_read120_ap_vld : IN STD_LOGIC;
    p_read121_ap_vld : IN STD_LOGIC;
    p_read122_ap_vld : IN STD_LOGIC;
    p_read123_ap_vld : IN STD_LOGIC;
    p_read124_ap_vld : IN STD_LOGIC;
    p_read125_ap_vld : IN STD_LOGIC;
    p_read126_ap_vld : IN STD_LOGIC;
    p_read127_ap_vld : IN STD_LOGIC;
    result_i_ap_vld : IN STD_LOGIC;
    result_o_ap_vld : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of tancalc_dataflow_parent_loop_proc is 
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv17_10000 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WVALID : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WLAST : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_RREADY : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_m_axi_input_V_BREADY : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_result_o : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_ap_start : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_result_o_ap_vld : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_ap_done : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_ap_ready : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_ap_idle : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_ap_continue : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal loop_dataflow_input_count : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal loop_dataflow_output_count : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal bound_minus_1 : STD_LOGIC_VECTOR (16 downto 0);
    signal dataflow_in_loop_calculation_loop_U0_start_full_n : STD_LOGIC;
    signal dataflow_in_loop_calculation_loop_U0_start_write : STD_LOGIC;

    component tancalc_dataflow_in_loop_calculation_loop IS
    port (
        m_axi_input_V_AWVALID : OUT STD_LOGIC;
        m_axi_input_V_AWREADY : IN STD_LOGIC;
        m_axi_input_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_input_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_input_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_input_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_input_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_input_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_input_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_input_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_input_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_input_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_input_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_input_V_WVALID : OUT STD_LOGIC;
        m_axi_input_V_WREADY : IN STD_LOGIC;
        m_axi_input_V_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_input_V_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_input_V_WLAST : OUT STD_LOGIC;
        m_axi_input_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_input_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_input_V_ARVALID : OUT STD_LOGIC;
        m_axi_input_V_ARREADY : IN STD_LOGIC;
        m_axi_input_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_input_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_input_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_input_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_input_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_input_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_input_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_input_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_input_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_input_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_input_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_input_V_RVALID : IN STD_LOGIC;
        m_axi_input_V_RREADY : OUT STD_LOGIC;
        m_axi_input_V_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_input_V_RLAST : IN STD_LOGIC;
        m_axi_input_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_input_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_input_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_input_V_BVALID : IN STD_LOGIC;
        m_axi_input_V_BREADY : OUT STD_LOGIC;
        m_axi_input_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_input_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_input_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        input_V_offset : IN STD_LOGIC_VECTOR (57 downto 0);
        ref_chunk_num_0_i : IN STD_LOGIC_VECTOR (16 downto 0);
        p_read : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read16 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read17 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read18 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read19 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read20 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read21 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read22 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read23 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read24 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read25 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read26 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read27 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read28 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read29 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read30 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read31 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read32 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read33 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read34 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read35 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read36 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read37 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read38 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read39 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read40 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read41 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read42 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read43 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read44 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read45 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read46 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read47 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read48 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read49 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read50 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read51 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read52 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read53 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read54 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read55 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read56 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read57 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read58 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read59 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read60 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read61 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read62 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read63 : IN STD_LOGIC_VECTOR (1023 downto 0);
        p_read64 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read65 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read66 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read67 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read68 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read69 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read70 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read71 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read72 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read73 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read74 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read75 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read76 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read77 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read78 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read79 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read80 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read81 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read82 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read83 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read84 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read85 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read86 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read87 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read88 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read89 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read90 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read91 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read92 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read93 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read94 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read95 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read96 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read97 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read98 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read99 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read100 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read101 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read102 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read103 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read104 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read105 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read106 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read107 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read108 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read109 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read110 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read111 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read112 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read113 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read114 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read115 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read116 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read117 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read118 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read119 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read120 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read121 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read122 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read123 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read124 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read125 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read126 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read127 : IN STD_LOGIC_VECTOR (10 downto 0);
        result_i : IN STD_LOGIC_VECTOR (31 downto 0);
        result_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        input_V_offset_ap_vld : IN STD_LOGIC;
        ref_chunk_num_0_i_ap_vld : IN STD_LOGIC;
        p_read_ap_vld : IN STD_LOGIC;
        p_read1_ap_vld : IN STD_LOGIC;
        p_read2_ap_vld : IN STD_LOGIC;
        p_read3_ap_vld : IN STD_LOGIC;
        p_read4_ap_vld : IN STD_LOGIC;
        p_read5_ap_vld : IN STD_LOGIC;
        p_read6_ap_vld : IN STD_LOGIC;
        p_read7_ap_vld : IN STD_LOGIC;
        p_read8_ap_vld : IN STD_LOGIC;
        p_read9_ap_vld : IN STD_LOGIC;
        p_read10_ap_vld : IN STD_LOGIC;
        p_read11_ap_vld : IN STD_LOGIC;
        p_read12_ap_vld : IN STD_LOGIC;
        p_read13_ap_vld : IN STD_LOGIC;
        p_read14_ap_vld : IN STD_LOGIC;
        p_read15_ap_vld : IN STD_LOGIC;
        p_read16_ap_vld : IN STD_LOGIC;
        p_read17_ap_vld : IN STD_LOGIC;
        p_read18_ap_vld : IN STD_LOGIC;
        p_read19_ap_vld : IN STD_LOGIC;
        p_read20_ap_vld : IN STD_LOGIC;
        p_read21_ap_vld : IN STD_LOGIC;
        p_read22_ap_vld : IN STD_LOGIC;
        p_read23_ap_vld : IN STD_LOGIC;
        p_read24_ap_vld : IN STD_LOGIC;
        p_read25_ap_vld : IN STD_LOGIC;
        p_read26_ap_vld : IN STD_LOGIC;
        p_read27_ap_vld : IN STD_LOGIC;
        p_read28_ap_vld : IN STD_LOGIC;
        p_read29_ap_vld : IN STD_LOGIC;
        p_read30_ap_vld : IN STD_LOGIC;
        p_read31_ap_vld : IN STD_LOGIC;
        p_read32_ap_vld : IN STD_LOGIC;
        p_read33_ap_vld : IN STD_LOGIC;
        p_read34_ap_vld : IN STD_LOGIC;
        p_read35_ap_vld : IN STD_LOGIC;
        p_read36_ap_vld : IN STD_LOGIC;
        p_read37_ap_vld : IN STD_LOGIC;
        p_read38_ap_vld : IN STD_LOGIC;
        p_read39_ap_vld : IN STD_LOGIC;
        p_read40_ap_vld : IN STD_LOGIC;
        p_read41_ap_vld : IN STD_LOGIC;
        p_read42_ap_vld : IN STD_LOGIC;
        p_read43_ap_vld : IN STD_LOGIC;
        p_read44_ap_vld : IN STD_LOGIC;
        p_read45_ap_vld : IN STD_LOGIC;
        p_read46_ap_vld : IN STD_LOGIC;
        p_read47_ap_vld : IN STD_LOGIC;
        p_read48_ap_vld : IN STD_LOGIC;
        p_read49_ap_vld : IN STD_LOGIC;
        p_read50_ap_vld : IN STD_LOGIC;
        p_read51_ap_vld : IN STD_LOGIC;
        p_read52_ap_vld : IN STD_LOGIC;
        p_read53_ap_vld : IN STD_LOGIC;
        p_read54_ap_vld : IN STD_LOGIC;
        p_read55_ap_vld : IN STD_LOGIC;
        p_read56_ap_vld : IN STD_LOGIC;
        p_read57_ap_vld : IN STD_LOGIC;
        p_read58_ap_vld : IN STD_LOGIC;
        p_read59_ap_vld : IN STD_LOGIC;
        p_read60_ap_vld : IN STD_LOGIC;
        p_read61_ap_vld : IN STD_LOGIC;
        p_read62_ap_vld : IN STD_LOGIC;
        p_read63_ap_vld : IN STD_LOGIC;
        p_read64_ap_vld : IN STD_LOGIC;
        p_read65_ap_vld : IN STD_LOGIC;
        p_read66_ap_vld : IN STD_LOGIC;
        p_read67_ap_vld : IN STD_LOGIC;
        p_read68_ap_vld : IN STD_LOGIC;
        p_read69_ap_vld : IN STD_LOGIC;
        p_read70_ap_vld : IN STD_LOGIC;
        p_read71_ap_vld : IN STD_LOGIC;
        p_read72_ap_vld : IN STD_LOGIC;
        p_read73_ap_vld : IN STD_LOGIC;
        p_read74_ap_vld : IN STD_LOGIC;
        p_read75_ap_vld : IN STD_LOGIC;
        p_read76_ap_vld : IN STD_LOGIC;
        p_read77_ap_vld : IN STD_LOGIC;
        p_read78_ap_vld : IN STD_LOGIC;
        p_read79_ap_vld : IN STD_LOGIC;
        p_read80_ap_vld : IN STD_LOGIC;
        p_read81_ap_vld : IN STD_LOGIC;
        p_read82_ap_vld : IN STD_LOGIC;
        p_read83_ap_vld : IN STD_LOGIC;
        p_read84_ap_vld : IN STD_LOGIC;
        p_read85_ap_vld : IN STD_LOGIC;
        p_read86_ap_vld : IN STD_LOGIC;
        p_read87_ap_vld : IN STD_LOGIC;
        p_read88_ap_vld : IN STD_LOGIC;
        p_read89_ap_vld : IN STD_LOGIC;
        p_read90_ap_vld : IN STD_LOGIC;
        p_read91_ap_vld : IN STD_LOGIC;
        p_read92_ap_vld : IN STD_LOGIC;
        p_read93_ap_vld : IN STD_LOGIC;
        p_read94_ap_vld : IN STD_LOGIC;
        p_read95_ap_vld : IN STD_LOGIC;
        p_read96_ap_vld : IN STD_LOGIC;
        p_read97_ap_vld : IN STD_LOGIC;
        p_read98_ap_vld : IN STD_LOGIC;
        p_read99_ap_vld : IN STD_LOGIC;
        p_read100_ap_vld : IN STD_LOGIC;
        p_read101_ap_vld : IN STD_LOGIC;
        p_read102_ap_vld : IN STD_LOGIC;
        p_read103_ap_vld : IN STD_LOGIC;
        p_read104_ap_vld : IN STD_LOGIC;
        p_read105_ap_vld : IN STD_LOGIC;
        p_read106_ap_vld : IN STD_LOGIC;
        p_read107_ap_vld : IN STD_LOGIC;
        p_read108_ap_vld : IN STD_LOGIC;
        p_read109_ap_vld : IN STD_LOGIC;
        p_read110_ap_vld : IN STD_LOGIC;
        p_read111_ap_vld : IN STD_LOGIC;
        p_read112_ap_vld : IN STD_LOGIC;
        p_read113_ap_vld : IN STD_LOGIC;
        p_read114_ap_vld : IN STD_LOGIC;
        p_read115_ap_vld : IN STD_LOGIC;
        p_read116_ap_vld : IN STD_LOGIC;
        p_read117_ap_vld : IN STD_LOGIC;
        p_read118_ap_vld : IN STD_LOGIC;
        p_read119_ap_vld : IN STD_LOGIC;
        p_read120_ap_vld : IN STD_LOGIC;
        p_read121_ap_vld : IN STD_LOGIC;
        p_read122_ap_vld : IN STD_LOGIC;
        p_read123_ap_vld : IN STD_LOGIC;
        p_read124_ap_vld : IN STD_LOGIC;
        p_read125_ap_vld : IN STD_LOGIC;
        p_read126_ap_vld : IN STD_LOGIC;
        p_read127_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        result_i_ap_vld : IN STD_LOGIC;
        result_o_ap_vld : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    dataflow_in_loop_calculation_loop_U0 : component tancalc_dataflow_in_loop_calculation_loop
    port map (
        m_axi_input_V_AWVALID => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWVALID,
        m_axi_input_V_AWREADY => ap_const_logic_0,
        m_axi_input_V_AWADDR => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWADDR,
        m_axi_input_V_AWID => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWID,
        m_axi_input_V_AWLEN => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWLEN,
        m_axi_input_V_AWSIZE => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWSIZE,
        m_axi_input_V_AWBURST => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWBURST,
        m_axi_input_V_AWLOCK => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWLOCK,
        m_axi_input_V_AWCACHE => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWCACHE,
        m_axi_input_V_AWPROT => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWPROT,
        m_axi_input_V_AWQOS => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWQOS,
        m_axi_input_V_AWREGION => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWREGION,
        m_axi_input_V_AWUSER => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_AWUSER,
        m_axi_input_V_WVALID => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WVALID,
        m_axi_input_V_WREADY => ap_const_logic_0,
        m_axi_input_V_WDATA => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WDATA,
        m_axi_input_V_WSTRB => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WSTRB,
        m_axi_input_V_WLAST => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WLAST,
        m_axi_input_V_WID => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WID,
        m_axi_input_V_WUSER => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_WUSER,
        m_axi_input_V_ARVALID => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARVALID,
        m_axi_input_V_ARREADY => m_axi_input_V_ARREADY,
        m_axi_input_V_ARADDR => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARADDR,
        m_axi_input_V_ARID => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARID,
        m_axi_input_V_ARLEN => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLEN,
        m_axi_input_V_ARSIZE => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARSIZE,
        m_axi_input_V_ARBURST => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARBURST,
        m_axi_input_V_ARLOCK => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLOCK,
        m_axi_input_V_ARCACHE => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARCACHE,
        m_axi_input_V_ARPROT => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARPROT,
        m_axi_input_V_ARQOS => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARQOS,
        m_axi_input_V_ARREGION => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARREGION,
        m_axi_input_V_ARUSER => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARUSER,
        m_axi_input_V_RVALID => m_axi_input_V_RVALID,
        m_axi_input_V_RREADY => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_RREADY,
        m_axi_input_V_RDATA => m_axi_input_V_RDATA,
        m_axi_input_V_RLAST => m_axi_input_V_RLAST,
        m_axi_input_V_RID => m_axi_input_V_RID,
        m_axi_input_V_RUSER => m_axi_input_V_RUSER,
        m_axi_input_V_RRESP => m_axi_input_V_RRESP,
        m_axi_input_V_BVALID => ap_const_logic_0,
        m_axi_input_V_BREADY => dataflow_in_loop_calculation_loop_U0_m_axi_input_V_BREADY,
        m_axi_input_V_BRESP => ap_const_lv2_0,
        m_axi_input_V_BID => ap_const_lv1_0,
        m_axi_input_V_BUSER => ap_const_lv1_0,
        input_V_offset => input_V_offset,
        ref_chunk_num_0_i => loop_dataflow_input_count,
        p_read => p_read,
        p_read1 => p_read1,
        p_read2 => p_read2,
        p_read3 => p_read3,
        p_read4 => p_read4,
        p_read5 => p_read5,
        p_read6 => p_read6,
        p_read7 => p_read7,
        p_read8 => p_read8,
        p_read9 => p_read9,
        p_read10 => p_read10,
        p_read11 => p_read11,
        p_read12 => p_read12,
        p_read13 => p_read13,
        p_read14 => p_read14,
        p_read15 => p_read15,
        p_read16 => p_read16,
        p_read17 => p_read17,
        p_read18 => p_read18,
        p_read19 => p_read19,
        p_read20 => p_read20,
        p_read21 => p_read21,
        p_read22 => p_read22,
        p_read23 => p_read23,
        p_read24 => p_read24,
        p_read25 => p_read25,
        p_read26 => p_read26,
        p_read27 => p_read27,
        p_read28 => p_read28,
        p_read29 => p_read29,
        p_read30 => p_read30,
        p_read31 => p_read31,
        p_read32 => p_read32,
        p_read33 => p_read33,
        p_read34 => p_read34,
        p_read35 => p_read35,
        p_read36 => p_read36,
        p_read37 => p_read37,
        p_read38 => p_read38,
        p_read39 => p_read39,
        p_read40 => p_read40,
        p_read41 => p_read41,
        p_read42 => p_read42,
        p_read43 => p_read43,
        p_read44 => p_read44,
        p_read45 => p_read45,
        p_read46 => p_read46,
        p_read47 => p_read47,
        p_read48 => p_read48,
        p_read49 => p_read49,
        p_read50 => p_read50,
        p_read51 => p_read51,
        p_read52 => p_read52,
        p_read53 => p_read53,
        p_read54 => p_read54,
        p_read55 => p_read55,
        p_read56 => p_read56,
        p_read57 => p_read57,
        p_read58 => p_read58,
        p_read59 => p_read59,
        p_read60 => p_read60,
        p_read61 => p_read61,
        p_read62 => p_read62,
        p_read63 => p_read63,
        p_read64 => p_read64,
        p_read65 => p_read65,
        p_read66 => p_read66,
        p_read67 => p_read67,
        p_read68 => p_read68,
        p_read69 => p_read69,
        p_read70 => p_read70,
        p_read71 => p_read71,
        p_read72 => p_read72,
        p_read73 => p_read73,
        p_read74 => p_read74,
        p_read75 => p_read75,
        p_read76 => p_read76,
        p_read77 => p_read77,
        p_read78 => p_read78,
        p_read79 => p_read79,
        p_read80 => p_read80,
        p_read81 => p_read81,
        p_read82 => p_read82,
        p_read83 => p_read83,
        p_read84 => p_read84,
        p_read85 => p_read85,
        p_read86 => p_read86,
        p_read87 => p_read87,
        p_read88 => p_read88,
        p_read89 => p_read89,
        p_read90 => p_read90,
        p_read91 => p_read91,
        p_read92 => p_read92,
        p_read93 => p_read93,
        p_read94 => p_read94,
        p_read95 => p_read95,
        p_read96 => p_read96,
        p_read97 => p_read97,
        p_read98 => p_read98,
        p_read99 => p_read99,
        p_read100 => p_read100,
        p_read101 => p_read101,
        p_read102 => p_read102,
        p_read103 => p_read103,
        p_read104 => p_read104,
        p_read105 => p_read105,
        p_read106 => p_read106,
        p_read107 => p_read107,
        p_read108 => p_read108,
        p_read109 => p_read109,
        p_read110 => p_read110,
        p_read111 => p_read111,
        p_read112 => p_read112,
        p_read113 => p_read113,
        p_read114 => p_read114,
        p_read115 => p_read115,
        p_read116 => p_read116,
        p_read117 => p_read117,
        p_read118 => p_read118,
        p_read119 => p_read119,
        p_read120 => p_read120,
        p_read121 => p_read121,
        p_read122 => p_read122,
        p_read123 => p_read123,
        p_read124 => p_read124,
        p_read125 => p_read125,
        p_read126 => p_read126,
        p_read127 => p_read127,
        result_i => result_i,
        result_o => dataflow_in_loop_calculation_loop_U0_result_o,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        input_V_offset_ap_vld => input_V_offset_ap_vld,
        ref_chunk_num_0_i_ap_vld => ap_const_logic_0,
        p_read_ap_vld => p_read_ap_vld,
        p_read1_ap_vld => p_read1_ap_vld,
        p_read2_ap_vld => p_read2_ap_vld,
        p_read3_ap_vld => p_read3_ap_vld,
        p_read4_ap_vld => p_read4_ap_vld,
        p_read5_ap_vld => p_read5_ap_vld,
        p_read6_ap_vld => p_read6_ap_vld,
        p_read7_ap_vld => p_read7_ap_vld,
        p_read8_ap_vld => p_read8_ap_vld,
        p_read9_ap_vld => p_read9_ap_vld,
        p_read10_ap_vld => p_read10_ap_vld,
        p_read11_ap_vld => p_read11_ap_vld,
        p_read12_ap_vld => p_read12_ap_vld,
        p_read13_ap_vld => p_read13_ap_vld,
        p_read14_ap_vld => p_read14_ap_vld,
        p_read15_ap_vld => p_read15_ap_vld,
        p_read16_ap_vld => p_read16_ap_vld,
        p_read17_ap_vld => p_read17_ap_vld,
        p_read18_ap_vld => p_read18_ap_vld,
        p_read19_ap_vld => p_read19_ap_vld,
        p_read20_ap_vld => p_read20_ap_vld,
        p_read21_ap_vld => p_read21_ap_vld,
        p_read22_ap_vld => p_read22_ap_vld,
        p_read23_ap_vld => p_read23_ap_vld,
        p_read24_ap_vld => p_read24_ap_vld,
        p_read25_ap_vld => p_read25_ap_vld,
        p_read26_ap_vld => p_read26_ap_vld,
        p_read27_ap_vld => p_read27_ap_vld,
        p_read28_ap_vld => p_read28_ap_vld,
        p_read29_ap_vld => p_read29_ap_vld,
        p_read30_ap_vld => p_read30_ap_vld,
        p_read31_ap_vld => p_read31_ap_vld,
        p_read32_ap_vld => p_read32_ap_vld,
        p_read33_ap_vld => p_read33_ap_vld,
        p_read34_ap_vld => p_read34_ap_vld,
        p_read35_ap_vld => p_read35_ap_vld,
        p_read36_ap_vld => p_read36_ap_vld,
        p_read37_ap_vld => p_read37_ap_vld,
        p_read38_ap_vld => p_read38_ap_vld,
        p_read39_ap_vld => p_read39_ap_vld,
        p_read40_ap_vld => p_read40_ap_vld,
        p_read41_ap_vld => p_read41_ap_vld,
        p_read42_ap_vld => p_read42_ap_vld,
        p_read43_ap_vld => p_read43_ap_vld,
        p_read44_ap_vld => p_read44_ap_vld,
        p_read45_ap_vld => p_read45_ap_vld,
        p_read46_ap_vld => p_read46_ap_vld,
        p_read47_ap_vld => p_read47_ap_vld,
        p_read48_ap_vld => p_read48_ap_vld,
        p_read49_ap_vld => p_read49_ap_vld,
        p_read50_ap_vld => p_read50_ap_vld,
        p_read51_ap_vld => p_read51_ap_vld,
        p_read52_ap_vld => p_read52_ap_vld,
        p_read53_ap_vld => p_read53_ap_vld,
        p_read54_ap_vld => p_read54_ap_vld,
        p_read55_ap_vld => p_read55_ap_vld,
        p_read56_ap_vld => p_read56_ap_vld,
        p_read57_ap_vld => p_read57_ap_vld,
        p_read58_ap_vld => p_read58_ap_vld,
        p_read59_ap_vld => p_read59_ap_vld,
        p_read60_ap_vld => p_read60_ap_vld,
        p_read61_ap_vld => p_read61_ap_vld,
        p_read62_ap_vld => p_read62_ap_vld,
        p_read63_ap_vld => p_read63_ap_vld,
        p_read64_ap_vld => p_read64_ap_vld,
        p_read65_ap_vld => p_read65_ap_vld,
        p_read66_ap_vld => p_read66_ap_vld,
        p_read67_ap_vld => p_read67_ap_vld,
        p_read68_ap_vld => p_read68_ap_vld,
        p_read69_ap_vld => p_read69_ap_vld,
        p_read70_ap_vld => p_read70_ap_vld,
        p_read71_ap_vld => p_read71_ap_vld,
        p_read72_ap_vld => p_read72_ap_vld,
        p_read73_ap_vld => p_read73_ap_vld,
        p_read74_ap_vld => p_read74_ap_vld,
        p_read75_ap_vld => p_read75_ap_vld,
        p_read76_ap_vld => p_read76_ap_vld,
        p_read77_ap_vld => p_read77_ap_vld,
        p_read78_ap_vld => p_read78_ap_vld,
        p_read79_ap_vld => p_read79_ap_vld,
        p_read80_ap_vld => p_read80_ap_vld,
        p_read81_ap_vld => p_read81_ap_vld,
        p_read82_ap_vld => p_read82_ap_vld,
        p_read83_ap_vld => p_read83_ap_vld,
        p_read84_ap_vld => p_read84_ap_vld,
        p_read85_ap_vld => p_read85_ap_vld,
        p_read86_ap_vld => p_read86_ap_vld,
        p_read87_ap_vld => p_read87_ap_vld,
        p_read88_ap_vld => p_read88_ap_vld,
        p_read89_ap_vld => p_read89_ap_vld,
        p_read90_ap_vld => p_read90_ap_vld,
        p_read91_ap_vld => p_read91_ap_vld,
        p_read92_ap_vld => p_read92_ap_vld,
        p_read93_ap_vld => p_read93_ap_vld,
        p_read94_ap_vld => p_read94_ap_vld,
        p_read95_ap_vld => p_read95_ap_vld,
        p_read96_ap_vld => p_read96_ap_vld,
        p_read97_ap_vld => p_read97_ap_vld,
        p_read98_ap_vld => p_read98_ap_vld,
        p_read99_ap_vld => p_read99_ap_vld,
        p_read100_ap_vld => p_read100_ap_vld,
        p_read101_ap_vld => p_read101_ap_vld,
        p_read102_ap_vld => p_read102_ap_vld,
        p_read103_ap_vld => p_read103_ap_vld,
        p_read104_ap_vld => p_read104_ap_vld,
        p_read105_ap_vld => p_read105_ap_vld,
        p_read106_ap_vld => p_read106_ap_vld,
        p_read107_ap_vld => p_read107_ap_vld,
        p_read108_ap_vld => p_read108_ap_vld,
        p_read109_ap_vld => p_read109_ap_vld,
        p_read110_ap_vld => p_read110_ap_vld,
        p_read111_ap_vld => p_read111_ap_vld,
        p_read112_ap_vld => p_read112_ap_vld,
        p_read113_ap_vld => p_read113_ap_vld,
        p_read114_ap_vld => p_read114_ap_vld,
        p_read115_ap_vld => p_read115_ap_vld,
        p_read116_ap_vld => p_read116_ap_vld,
        p_read117_ap_vld => p_read117_ap_vld,
        p_read118_ap_vld => p_read118_ap_vld,
        p_read119_ap_vld => p_read119_ap_vld,
        p_read120_ap_vld => p_read120_ap_vld,
        p_read121_ap_vld => p_read121_ap_vld,
        p_read122_ap_vld => p_read122_ap_vld,
        p_read123_ap_vld => p_read123_ap_vld,
        p_read124_ap_vld => p_read124_ap_vld,
        p_read125_ap_vld => p_read125_ap_vld,
        p_read126_ap_vld => p_read126_ap_vld,
        p_read127_ap_vld => p_read127_ap_vld,
        ap_start => dataflow_in_loop_calculation_loop_U0_ap_start,
        result_i_ap_vld => result_i_ap_vld,
        result_o_ap_vld => dataflow_in_loop_calculation_loop_U0_result_o_ap_vld,
        ap_done => dataflow_in_loop_calculation_loop_U0_ap_done,
        ap_ready => dataflow_in_loop_calculation_loop_U0_ap_ready,
        ap_idle => dataflow_in_loop_calculation_loop_U0_ap_idle,
        ap_continue => dataflow_in_loop_calculation_loop_U0_ap_continue);





    loop_dataflow_input_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_input_count <= ap_const_lv17_0;
            else
                if ((not((loop_dataflow_input_count = bound_minus_1)) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_calculation_loop_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= std_logic_vector(unsigned(loop_dataflow_input_count) + unsigned(ap_const_lv17_1));
                elsif (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_calculation_loop_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= ap_const_lv17_0;
                end if; 
            end if;
        end if;
    end process;


    loop_dataflow_output_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_output_count <= ap_const_lv17_0;
            else
                if ((not((loop_dataflow_output_count = bound_minus_1)) and (dataflow_in_loop_calculation_loop_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_calculation_loop_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= std_logic_vector(unsigned(loop_dataflow_output_count) + unsigned(ap_const_lv17_1));
                elsif (((loop_dataflow_output_count = bound_minus_1) and (dataflow_in_loop_calculation_loop_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_calculation_loop_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= ap_const_lv17_0;
                end if; 
            end if;
        end if;
    end process;


    ap_done_assign_proc : process(dataflow_in_loop_calculation_loop_U0_ap_done, loop_dataflow_output_count, bound_minus_1)
    begin
        if (((loop_dataflow_output_count = bound_minus_1) and (dataflow_in_loop_calculation_loop_U0_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(dataflow_in_loop_calculation_loop_U0_ap_idle, ap_start, loop_dataflow_output_count)
    begin
        if (((loop_dataflow_output_count = ap_const_lv17_0) and (ap_start = ap_const_logic_0) and (dataflow_in_loop_calculation_loop_U0_ap_idle = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(dataflow_in_loop_calculation_loop_U0_ap_ready, ap_start, loop_dataflow_input_count, bound_minus_1)
    begin
        if (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_calculation_loop_U0_ap_ready = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_sync_continue <= ap_continue;
    ap_sync_done <= dataflow_in_loop_calculation_loop_U0_ap_done;
    ap_sync_ready <= dataflow_in_loop_calculation_loop_U0_ap_ready;
    bound_minus_1 <= std_logic_vector(unsigned(ap_const_lv17_10000) - unsigned(ap_const_lv17_1));

    dataflow_in_loop_calculation_loop_U0_ap_continue_assign_proc : process(ap_continue, loop_dataflow_output_count, bound_minus_1)
    begin
        if ((not((loop_dataflow_output_count = bound_minus_1)) or (ap_continue = ap_const_logic_1))) then 
            dataflow_in_loop_calculation_loop_U0_ap_continue <= ap_const_logic_1;
        else 
            dataflow_in_loop_calculation_loop_U0_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    dataflow_in_loop_calculation_loop_U0_ap_start <= ap_start;
    dataflow_in_loop_calculation_loop_U0_start_full_n <= ap_const_logic_1;
    dataflow_in_loop_calculation_loop_U0_start_write <= ap_const_logic_0;
    m_axi_input_V_ARADDR <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARADDR;
    m_axi_input_V_ARBURST <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARBURST;
    m_axi_input_V_ARCACHE <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARCACHE;
    m_axi_input_V_ARID <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARID;
    m_axi_input_V_ARLEN <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLEN;
    m_axi_input_V_ARLOCK <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARLOCK;
    m_axi_input_V_ARPROT <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARPROT;
    m_axi_input_V_ARQOS <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARQOS;
    m_axi_input_V_ARREGION <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARREGION;
    m_axi_input_V_ARSIZE <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARSIZE;
    m_axi_input_V_ARUSER <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARUSER;
    m_axi_input_V_ARVALID <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_ARVALID;
    m_axi_input_V_AWADDR <= ap_const_lv64_0;
    m_axi_input_V_AWBURST <= ap_const_lv2_0;
    m_axi_input_V_AWCACHE <= ap_const_lv4_0;
    m_axi_input_V_AWID <= ap_const_lv1_0;
    m_axi_input_V_AWLEN <= ap_const_lv32_0;
    m_axi_input_V_AWLOCK <= ap_const_lv2_0;
    m_axi_input_V_AWPROT <= ap_const_lv3_0;
    m_axi_input_V_AWQOS <= ap_const_lv4_0;
    m_axi_input_V_AWREGION <= ap_const_lv4_0;
    m_axi_input_V_AWSIZE <= ap_const_lv3_0;
    m_axi_input_V_AWUSER <= ap_const_lv1_0;
    m_axi_input_V_AWVALID <= ap_const_logic_0;
    m_axi_input_V_BREADY <= ap_const_logic_0;
    m_axi_input_V_RREADY <= dataflow_in_loop_calculation_loop_U0_m_axi_input_V_RREADY;
    m_axi_input_V_WDATA <= ap_const_lv512_lc_1;
    m_axi_input_V_WID <= ap_const_lv1_0;
    m_axi_input_V_WLAST <= ap_const_logic_0;
    m_axi_input_V_WSTRB <= ap_const_lv64_0;
    m_axi_input_V_WUSER <= ap_const_lv1_0;
    m_axi_input_V_WVALID <= ap_const_logic_0;
    result_o <= dataflow_in_loop_calculation_loop_U0_result_o;
    result_o_ap_vld <= dataflow_in_loop_calculation_loop_U0_result_o_ap_vld;
end behav;
